//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.EnNmberService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnterpriseEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL")]
    [System.SerializableAttribute()]
    public partial class EnterpriseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactsTelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterprisePwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IS_UsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialPwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactsTel {
            get {
                return this.ContactsTelField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsTelField, value) != true)) {
                    this.ContactsTelField = value;
                    this.RaisePropertyChanged("ContactsTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseCode {
            get {
                return this.EnterpriseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseCodeField, value) != true)) {
                    this.EnterpriseCodeField = value;
                    this.RaisePropertyChanged("EnterpriseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseName {
            get {
                return this.EnterpriseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseNameField, value) != true)) {
                    this.EnterpriseNameField = value;
                    this.RaisePropertyChanged("EnterpriseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseNumber {
            get {
                return this.EnterpriseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseNumberField, value) != true)) {
                    this.EnterpriseNumberField = value;
                    this.RaisePropertyChanged("EnterpriseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterprisePwd {
            get {
                return this.EnterprisePwdField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterprisePwdField, value) != true)) {
                    this.EnterprisePwdField = value;
                    this.RaisePropertyChanged("EnterprisePwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IS_Used {
            get {
                return this.IS_UsedField;
            }
            set {
                if ((this.IS_UsedField.Equals(value) != true)) {
                    this.IS_UsedField = value;
                    this.RaisePropertyChanged("IS_Used");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialPwd {
            get {
                return this.SerialPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialPwdField, value) != true)) {
                    this.SerialPwdField = value;
                    this.RaisePropertyChanged("SerialPwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTime {
            get {
                return this.ValidTimeField;
            }
            set {
                if ((this.ValidTimeField.Equals(value) != true)) {
                    this.ValidTimeField = value;
                    this.RaisePropertyChanged("ValidTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnNmberService.IEnterpriseService")]
    public interface IEnterpriseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/AddEnterprise", ReplyAction="http://tempuri.org/IEnterpriseService/AddEnterpriseResponse")]
        int AddEnterprise(WebPages.EnNmberService.EnterpriseEntity info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/GetEnterpriseTemp", ReplyAction="http://tempuri.org/IEnterpriseService/GetEnterpriseTempResponse")]
        System.Data.DataSet GetEnterpriseTemp(int StarPages, int EndPages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/GetAmountDS", ReplyAction="http://tempuri.org/IEnterpriseService/GetAmountDSResponse")]
        System.Data.DataSet GetAmountDS(string AmountCode, string DisplayName, string Pinyin, int TypeID, int StartIndex, int EndIndex, string E_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/GetAmountTypeTemp", ReplyAction="http://tempuri.org/IEnterpriseService/GetAmountTypeTempResponse")]
        System.Data.DataTable GetAmountTypeTemp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/GetAmountRemarkTemp", ReplyAction="http://tempuri.org/IEnterpriseService/GetAmountRemarkTempResponse")]
        System.Data.DataTable GetAmountRemarkTemp(string AmountCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/EditAR", ReplyAction="http://tempuri.org/IEnterpriseService/EditARResponse")]
        int EditAR(string Amount_Code, string AmountIntroduce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/AuthorizationLB", ReplyAction="http://tempuri.org/IEnterpriseService/AuthorizationLBResponse")]
        int AuthorizationLB(string LicenseCode, string Amount_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/Del_AmountLicense", ReplyAction="http://tempuri.org/IEnterpriseService/Del_AmountLicenseResponse")]
        int Del_AmountLicense(string LicenseCode, string Amount_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/UpdatePwd", ReplyAction="http://tempuri.org/IEnterpriseService/UpdatePwdResponse")]
        bool UpdatePwd(string EnterpriseCode, string EnterprisePwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/ModelUpdate", ReplyAction="http://tempuri.org/IEnterpriseService/ModelUpdateResponse")]
        bool ModelUpdate(WebPages.EnNmberService.EnterpriseEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/ModelSelect", ReplyAction="http://tempuri.org/IEnterpriseService/ModelSelectResponse")]
        WebPages.EnNmberService.EnterpriseEntity ModelSelect(string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/ENumbers", ReplyAction="http://tempuri.org/IEnterpriseService/ENumbersResponse")]
        bool ENumbers(string ENumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnterpriseService/ENumberNames", ReplyAction="http://tempuri.org/IEnterpriseService/ENumberNamesResponse")]
        WebPages.EnNmberService.EnterpriseEntity ENumberNames([System.ServiceModel.MessageParameterAttribute(Name="ENumberNames")] string ENumberNames1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnterpriseServiceChannel : WebPages.EnNmberService.IEnterpriseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnterpriseServiceClient : System.ServiceModel.ClientBase<WebPages.EnNmberService.IEnterpriseService>, WebPages.EnNmberService.IEnterpriseService {
        
        public EnterpriseServiceClient() {
        }
        
        public EnterpriseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnterpriseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddEnterprise(WebPages.EnNmberService.EnterpriseEntity info) {
            return base.Channel.AddEnterprise(info);
        }
        
        public System.Data.DataSet GetEnterpriseTemp(int StarPages, int EndPages) {
            return base.Channel.GetEnterpriseTemp(StarPages, EndPages);
        }
        
        public System.Data.DataSet GetAmountDS(string AmountCode, string DisplayName, string Pinyin, int TypeID, int StartIndex, int EndIndex, string E_Code) {
            return base.Channel.GetAmountDS(AmountCode, DisplayName, Pinyin, TypeID, StartIndex, EndIndex, E_Code);
        }
        
        public System.Data.DataTable GetAmountTypeTemp() {
            return base.Channel.GetAmountTypeTemp();
        }
        
        public System.Data.DataTable GetAmountRemarkTemp(string AmountCode) {
            return base.Channel.GetAmountRemarkTemp(AmountCode);
        }
        
        public int EditAR(string Amount_Code, string AmountIntroduce) {
            return base.Channel.EditAR(Amount_Code, AmountIntroduce);
        }
        
        public int AuthorizationLB(string LicenseCode, string Amount_Code) {
            return base.Channel.AuthorizationLB(LicenseCode, Amount_Code);
        }
        
        public int Del_AmountLicense(string LicenseCode, string Amount_Code) {
            return base.Channel.Del_AmountLicense(LicenseCode, Amount_Code);
        }
        
        public bool UpdatePwd(string EnterpriseCode, string EnterprisePwd) {
            return base.Channel.UpdatePwd(EnterpriseCode, EnterprisePwd);
        }
        
        public bool ModelUpdate(WebPages.EnNmberService.EnterpriseEntity entityInfo) {
            return base.Channel.ModelUpdate(entityInfo);
        }
        
        public WebPages.EnNmberService.EnterpriseEntity ModelSelect(string EnterpriseCode) {
            return base.Channel.ModelSelect(EnterpriseCode);
        }
        
        public bool ENumbers(string ENumber) {
            return base.Channel.ENumbers(ENumber);
        }
        
        public WebPages.EnNmberService.EnterpriseEntity ENumberNames(string ENumberNames1) {
            return base.Channel.ENumberNames(ENumberNames1);
        }
    }
}
