//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.AmountTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmountTypeService.IAmountTypeService")]
    public interface IAmountTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmountTypeService/GetAmountTypeTemp", ReplyAction="http://tempuri.org/IAmountTypeService/GetAmountTypeTempResponse")]
        System.Data.DataTable GetAmountTypeTemp(string EnterpriseCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmountTypeServiceChannel : WebPages.AmountTypeService.IAmountTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmountTypeServiceClient : System.ServiceModel.ClientBase<WebPages.AmountTypeService.IAmountTypeService>, WebPages.AmountTypeService.IAmountTypeService {
        
        public AmountTypeServiceClient() {
        }
        
        public AmountTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmountTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmountTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmountTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAmountTypeTemp(string EnterpriseCode) {
            return base.Channel.GetAmountTypeTemp(EnterpriseCode);
        }
    }
}
