//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.RoleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.BasicSettingModel")]
    [System.SerializableAttribute()]
    public partial class RoleEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_CreatePersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Role_CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_DescribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_EditPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Role_EditTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Role_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Role_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role_CreatePerson {
            get {
                return this.Role_CreatePersonField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_CreatePersonField, value) != true)) {
                    this.Role_CreatePersonField = value;
                    this.RaisePropertyChanged("Role_CreatePerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Role_CreateTime {
            get {
                return this.Role_CreateTimeField;
            }
            set {
                if ((this.Role_CreateTimeField.Equals(value) != true)) {
                    this.Role_CreateTimeField = value;
                    this.RaisePropertyChanged("Role_CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role_Describe {
            get {
                return this.Role_DescribeField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_DescribeField, value) != true)) {
                    this.Role_DescribeField = value;
                    this.RaisePropertyChanged("Role_Describe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role_EditPerson {
            get {
                return this.Role_EditPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_EditPersonField, value) != true)) {
                    this.Role_EditPersonField = value;
                    this.RaisePropertyChanged("Role_EditPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Role_EditTime {
            get {
                return this.Role_EditTimeField;
            }
            set {
                if ((this.Role_EditTimeField.Equals(value) != true)) {
                    this.Role_EditTimeField = value;
                    this.RaisePropertyChanged("Role_EditTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role_ID {
            get {
                return this.Role_IDField;
            }
            set {
                if ((this.Role_IDField.Equals(value) != true)) {
                    this.Role_IDField = value;
                    this.RaisePropertyChanged("Role_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role_Name {
            get {
                return this.Role_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_NameField, value) != true)) {
                    this.Role_NameField = value;
                    this.RaisePropertyChanged("Role_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role_Type {
            get {
                return this.Role_TypeField;
            }
            set {
                if ((this.Role_TypeField.Equals(value) != true)) {
                    this.Role_TypeField = value;
                    this.RaisePropertyChanged("Role_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleTypeEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.BasicSettingModel")]
    [System.SerializableAttribute()]
    public partial class RoleTypeEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleType_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleType_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleType_ID {
            get {
                return this.RoleType_IDField;
            }
            set {
                if ((this.RoleType_IDField.Equals(value) != true)) {
                    this.RoleType_IDField = value;
                    this.RaisePropertyChanged("RoleType_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleType_Name {
            get {
                return this.RoleType_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleType_NameField, value) != true)) {
                    this.RoleType_NameField = value;
                    this.RaisePropertyChanged("RoleType_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoleService.IRoleService")]
    public interface IRoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/AddRole", ReplyAction="http://tempuri.org/IRoleService/AddRoleResponse")]
        bool AddRole(WebPages.RoleService.RoleEntity re);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/InitRoleList", ReplyAction="http://tempuri.org/IRoleService/InitRoleListResponse")]
        System.Data.DataSet InitRoleList(int userID, string enterpriseCode, string role_Name, int startPageIndex, int endPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Update", ReplyAction="http://tempuri.org/IRoleService/UpdateResponse")]
        bool Update(WebPages.RoleService.RoleEntity re);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Delete", ReplyAction="http://tempuri.org/IRoleService/DeleteResponse")]
        bool Delete(int roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetMemberCount", ReplyAction="http://tempuri.org/IRoleService/GetMemberCountResponse")]
        int GetMemberCount(int roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/UpdateRIsOpen", ReplyAction="http://tempuri.org/IRoleService/UpdateRIsOpenResponse")]
        bool UpdateRIsOpen(int RoleID, int IsOpen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetIsOpen", ReplyAction="http://tempuri.org/IRoleService/GetIsOpenResponse")]
        WebPages.RoleService.RoleEntity GetIsOpen(string LoginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/JudgeRoleName", ReplyAction="http://tempuri.org/IRoleService/JudgeRoleNameResponse")]
        bool JudgeRoleName(string roleName, int Role_ID, string enterpriseCode, int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/Getrole", ReplyAction="http://tempuri.org/IRoleService/GetroleResponse")]
        WebPages.RoleService.RoleEntity Getrole(int Role_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetAllRole", ReplyAction="http://tempuri.org/IRoleService/GetAllRoleResponse")]
        System.Collections.Generic.List<WebPages.RoleService.RoleEntity> GetAllRole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetRoleTypeList", ReplyAction="http://tempuri.org/IRoleService/GetRoleTypeListResponse")]
        System.Collections.Generic.List<WebPages.RoleService.RoleTypeEntity> GetRoleTypeList(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/IsRole", ReplyAction="http://tempuri.org/IRoleService/IsRoleResponse")]
        WebPages.RoleService.RoleEntity IsRole(int Role_Type, string RoleName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoleServiceChannel : WebPages.RoleService.IRoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleServiceClient : System.ServiceModel.ClientBase<WebPages.RoleService.IRoleService>, WebPages.RoleService.IRoleService {
        
        public RoleServiceClient() {
        }
        
        public RoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddRole(WebPages.RoleService.RoleEntity re) {
            return base.Channel.AddRole(re);
        }
        
        public System.Data.DataSet InitRoleList(int userID, string enterpriseCode, string role_Name, int startPageIndex, int endPageIndex) {
            return base.Channel.InitRoleList(userID, enterpriseCode, role_Name, startPageIndex, endPageIndex);
        }
        
        public bool Update(WebPages.RoleService.RoleEntity re) {
            return base.Channel.Update(re);
        }
        
        public bool Delete(int roleID) {
            return base.Channel.Delete(roleID);
        }
        
        public int GetMemberCount(int roleID) {
            return base.Channel.GetMemberCount(roleID);
        }
        
        public bool UpdateRIsOpen(int RoleID, int IsOpen) {
            return base.Channel.UpdateRIsOpen(RoleID, IsOpen);
        }
        
        public WebPages.RoleService.RoleEntity GetIsOpen(string LoginName) {
            return base.Channel.GetIsOpen(LoginName);
        }
        
        public bool JudgeRoleName(string roleName, int Role_ID, string enterpriseCode, int U_ID) {
            return base.Channel.JudgeRoleName(roleName, Role_ID, enterpriseCode, U_ID);
        }
        
        public WebPages.RoleService.RoleEntity Getrole(int Role_ID) {
            return base.Channel.Getrole(Role_ID);
        }
        
        public System.Collections.Generic.List<WebPages.RoleService.RoleEntity> GetAllRole() {
            return base.Channel.GetAllRole();
        }
        
        public System.Collections.Generic.List<WebPages.RoleService.RoleTypeEntity> GetRoleTypeList(int userID) {
            return base.Channel.GetRoleTypeList(userID);
        }
        
        public WebPages.RoleService.RoleEntity IsRole(int Role_Type, string RoleName) {
            return base.Channel.IsRole(Role_Type, RoleName);
        }
    }
}
