//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.RecycleBinService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecycleBinModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.RecycleBinModel")]
    [System.SerializableAttribute()]
    public partial class RecycleBinModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PB_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RBDeleteFieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RBDeleteTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RBExcutePersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RBFieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RBFieldValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RBIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RBModularIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RBTableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RBTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseCode {
            get {
                return this.EnterpriseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseCodeField, value) != true)) {
                    this.EnterpriseCodeField = value;
                    this.RaisePropertyChanged("EnterpriseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PB_Type {
            get {
                return this.PB_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PB_TypeField, value) != true)) {
                    this.PB_TypeField = value;
                    this.RaisePropertyChanged("PB_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RBDeleteFieldName {
            get {
                return this.RBDeleteFieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RBDeleteFieldNameField, value) != true)) {
                    this.RBDeleteFieldNameField = value;
                    this.RaisePropertyChanged("RBDeleteFieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RBDeleteTime {
            get {
                return this.RBDeleteTimeField;
            }
            set {
                if ((this.RBDeleteTimeField.Equals(value) != true)) {
                    this.RBDeleteTimeField = value;
                    this.RaisePropertyChanged("RBDeleteTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RBExcutePerson {
            get {
                return this.RBExcutePersonField;
            }
            set {
                if ((object.ReferenceEquals(this.RBExcutePersonField, value) != true)) {
                    this.RBExcutePersonField = value;
                    this.RaisePropertyChanged("RBExcutePerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RBFieldName {
            get {
                return this.RBFieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RBFieldNameField, value) != true)) {
                    this.RBFieldNameField = value;
                    this.RaisePropertyChanged("RBFieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RBFieldValue {
            get {
                return this.RBFieldValueField;
            }
            set {
                if ((object.ReferenceEquals(this.RBFieldValueField, value) != true)) {
                    this.RBFieldValueField = value;
                    this.RaisePropertyChanged("RBFieldValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RBID {
            get {
                return this.RBIDField;
            }
            set {
                if ((this.RBIDField.Equals(value) != true)) {
                    this.RBIDField = value;
                    this.RaisePropertyChanged("RBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RBModularID {
            get {
                return this.RBModularIDField;
            }
            set {
                if ((this.RBModularIDField.Equals(value) != true)) {
                    this.RBModularIDField = value;
                    this.RaisePropertyChanged("RBModularID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RBTableName {
            get {
                return this.RBTableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RBTableNameField, value) != true)) {
                    this.RBTableNameField = value;
                    this.RaisePropertyChanged("RBTableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RBTitle {
            get {
                return this.RBTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.RBTitleField, value) != true)) {
                    this.RBTitleField = value;
                    this.RaisePropertyChanged("RBTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecycleBinEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.RecycleBinModel")]
    [System.SerializableAttribute()]
    public partial class RecycleBinEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _enterpriseCodeField;
        
        private string _rbdeletefieldnameField;
        
        private System.DateTime _rbdeletetimeField;
        
        private string _rbexcutepersonField;
        
        private string _rbfieldnameField;
        
        private string _rbfieldvalueField;
        
        private int _rbidField;
        
        private int _rbisdeleteField;
        
        private int _rbmodularidField;
        
        private string _rbtablenameField;
        
        private string _rbtitleField;
        
        private string _typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _enterpriseCode {
            get {
                return this._enterpriseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this._enterpriseCodeField, value) != true)) {
                    this._enterpriseCodeField = value;
                    this.RaisePropertyChanged("_enterpriseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _rbdeletefieldname {
            get {
                return this._rbdeletefieldnameField;
            }
            set {
                if ((object.ReferenceEquals(this._rbdeletefieldnameField, value) != true)) {
                    this._rbdeletefieldnameField = value;
                    this.RaisePropertyChanged("_rbdeletefieldname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _rbdeletetime {
            get {
                return this._rbdeletetimeField;
            }
            set {
                if ((this._rbdeletetimeField.Equals(value) != true)) {
                    this._rbdeletetimeField = value;
                    this.RaisePropertyChanged("_rbdeletetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _rbexcuteperson {
            get {
                return this._rbexcutepersonField;
            }
            set {
                if ((object.ReferenceEquals(this._rbexcutepersonField, value) != true)) {
                    this._rbexcutepersonField = value;
                    this.RaisePropertyChanged("_rbexcuteperson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _rbfieldname {
            get {
                return this._rbfieldnameField;
            }
            set {
                if ((object.ReferenceEquals(this._rbfieldnameField, value) != true)) {
                    this._rbfieldnameField = value;
                    this.RaisePropertyChanged("_rbfieldname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _rbfieldvalue {
            get {
                return this._rbfieldvalueField;
            }
            set {
                if ((object.ReferenceEquals(this._rbfieldvalueField, value) != true)) {
                    this._rbfieldvalueField = value;
                    this.RaisePropertyChanged("_rbfieldvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _rbid {
            get {
                return this._rbidField;
            }
            set {
                if ((this._rbidField.Equals(value) != true)) {
                    this._rbidField = value;
                    this.RaisePropertyChanged("_rbid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _rbisdelete {
            get {
                return this._rbisdeleteField;
            }
            set {
                if ((this._rbisdeleteField.Equals(value) != true)) {
                    this._rbisdeleteField = value;
                    this.RaisePropertyChanged("_rbisdelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _rbmodularid {
            get {
                return this._rbmodularidField;
            }
            set {
                if ((this._rbmodularidField.Equals(value) != true)) {
                    this._rbmodularidField = value;
                    this.RaisePropertyChanged("_rbmodularid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _rbtablename {
            get {
                return this._rbtablenameField;
            }
            set {
                if ((object.ReferenceEquals(this._rbtablenameField, value) != true)) {
                    this._rbtablenameField = value;
                    this.RaisePropertyChanged("_rbtablename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _rbtitle {
            get {
                return this._rbtitleField;
            }
            set {
                if ((object.ReferenceEquals(this._rbtitleField, value) != true)) {
                    this._rbtitleField = value;
                    this.RaisePropertyChanged("_rbtitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _type {
            get {
                return this._typeField;
            }
            set {
                if ((object.ReferenceEquals(this._typeField, value) != true)) {
                    this._typeField = value;
                    this.RaisePropertyChanged("_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecycleBinService.IRecycleBinService")]
    public interface IRecycleBinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/InitiRecyleBinTable", ReplyAction="http://tempuri.org/IRecycleBinService/InitiRecyleBinTableResponse")]
        System.Data.DataSet InitiRecyleBinTable(int userID, int modularName, string enterpriseCode, int StarPageIndex, int EndPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/DeleteRecycleBinByRBID", ReplyAction="http://tempuri.org/IRecycleBinService/DeleteRecycleBinByRBIDResponse")]
        bool DeleteRecycleBinByRBID(int moduarID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/RestoreData", ReplyAction="http://tempuri.org/IRecycleBinService/RestoreDataResponse")]
        bool RestoreData(int rBID, string rBTableName, string rBFieldName, string rBFieldValue, string rBDeleteFieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/PutDataInRecycleBin", ReplyAction="http://tempuri.org/IRecycleBinService/PutDataInRecycleBinResponse")]
        bool PutDataInRecycleBin(WebPages.RecycleBinService.RecycleBinModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/Insert", ReplyAction="http://tempuri.org/IRecycleBinService/InsertResponse")]
        long Insert(WebPages.RecycleBinService.RecycleBinEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/InsertRecycleBin", ReplyAction="http://tempuri.org/IRecycleBinService/InsertRecycleBinResponse")]
        bool InsertRecycleBin(WebPages.RecycleBinService.RecycleBinModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/InsertData", ReplyAction="http://tempuri.org/IRecycleBinService/InsertDataResponse")]
        bool InsertData(int rBID, string rBTableName, string rBFieldName, string rBFieldValue, string rBDeleteFieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/counts", ReplyAction="http://tempuri.org/IRecycleBinService/countsResponse")]
        int counts(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecycleBinService/recydelete", ReplyAction="http://tempuri.org/IRecycleBinService/recydeleteResponse")]
        bool recydelete(string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecycleBinServiceChannel : WebPages.RecycleBinService.IRecycleBinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecycleBinServiceClient : System.ServiceModel.ClientBase<WebPages.RecycleBinService.IRecycleBinService>, WebPages.RecycleBinService.IRecycleBinService {
        
        public RecycleBinServiceClient() {
        }
        
        public RecycleBinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecycleBinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecycleBinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecycleBinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet InitiRecyleBinTable(int userID, int modularName, string enterpriseCode, int StarPageIndex, int EndPageIndex) {
            return base.Channel.InitiRecyleBinTable(userID, modularName, enterpriseCode, StarPageIndex, EndPageIndex);
        }
        
        public bool DeleteRecycleBinByRBID(int moduarID) {
            return base.Channel.DeleteRecycleBinByRBID(moduarID);
        }
        
        public bool RestoreData(int rBID, string rBTableName, string rBFieldName, string rBFieldValue, string rBDeleteFieldName) {
            return base.Channel.RestoreData(rBID, rBTableName, rBFieldName, rBFieldValue, rBDeleteFieldName);
        }
        
        public bool PutDataInRecycleBin(WebPages.RecycleBinService.RecycleBinModel model) {
            return base.Channel.PutDataInRecycleBin(model);
        }
        
        public long Insert(WebPages.RecycleBinService.RecycleBinEntity entityInfo) {
            return base.Channel.Insert(entityInfo);
        }
        
        public bool InsertRecycleBin(WebPages.RecycleBinService.RecycleBinModel model) {
            return base.Channel.InsertRecycleBin(model);
        }
        
        public bool InsertData(int rBID, string rBTableName, string rBFieldName, string rBFieldValue, string rBDeleteFieldName) {
            return base.Channel.InsertData(rBID, rBTableName, rBFieldName, rBFieldValue, rBDeleteFieldName);
        }
        
        public int counts(string userID) {
            return base.Channel.counts(userID);
        }
        
        public bool recydelete(string userID) {
            return base.Channel.recydelete(userID);
        }
    }
}
