//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.ReservationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YT_YuYueTimeEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.ReservationModel")]
    [System.SerializableAttribute()]
    public partial class YT_YuYueTimeEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _themidField;
        
        private System.DateTime _yt_bdateField;
        
        private string _yt_btimeField;
        
        private int _yt_conselingaddressField;
        
        private int _yt_conselingtypeField;
        
        private string _yt_createpersonField;
        
        private System.DateTime _yt_createtimeField;
        
        private string _yt_describeField;
        
        private System.DateTime _yt_edateField;
        
        private string _yt_etimeField;
        
        private int _yt_idField;
        
        private int _yt_stateField;
        
        private int _yt_useridField;
        
        private string _yt_weekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _themid {
            get {
                return this._themidField;
            }
            set {
                if ((this._themidField.Equals(value) != true)) {
                    this._themidField = value;
                    this.RaisePropertyChanged("_themid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _yt_bdate {
            get {
                return this._yt_bdateField;
            }
            set {
                if ((this._yt_bdateField.Equals(value) != true)) {
                    this._yt_bdateField = value;
                    this.RaisePropertyChanged("_yt_bdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yt_btime {
            get {
                return this._yt_btimeField;
            }
            set {
                if ((object.ReferenceEquals(this._yt_btimeField, value) != true)) {
                    this._yt_btimeField = value;
                    this.RaisePropertyChanged("_yt_btime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yt_conselingaddress {
            get {
                return this._yt_conselingaddressField;
            }
            set {
                if ((this._yt_conselingaddressField.Equals(value) != true)) {
                    this._yt_conselingaddressField = value;
                    this.RaisePropertyChanged("_yt_conselingaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yt_conselingtype {
            get {
                return this._yt_conselingtypeField;
            }
            set {
                if ((this._yt_conselingtypeField.Equals(value) != true)) {
                    this._yt_conselingtypeField = value;
                    this.RaisePropertyChanged("_yt_conselingtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yt_createperson {
            get {
                return this._yt_createpersonField;
            }
            set {
                if ((object.ReferenceEquals(this._yt_createpersonField, value) != true)) {
                    this._yt_createpersonField = value;
                    this.RaisePropertyChanged("_yt_createperson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _yt_createtime {
            get {
                return this._yt_createtimeField;
            }
            set {
                if ((this._yt_createtimeField.Equals(value) != true)) {
                    this._yt_createtimeField = value;
                    this.RaisePropertyChanged("_yt_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yt_describe {
            get {
                return this._yt_describeField;
            }
            set {
                if ((object.ReferenceEquals(this._yt_describeField, value) != true)) {
                    this._yt_describeField = value;
                    this.RaisePropertyChanged("_yt_describe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _yt_edate {
            get {
                return this._yt_edateField;
            }
            set {
                if ((this._yt_edateField.Equals(value) != true)) {
                    this._yt_edateField = value;
                    this.RaisePropertyChanged("_yt_edate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yt_etime {
            get {
                return this._yt_etimeField;
            }
            set {
                if ((object.ReferenceEquals(this._yt_etimeField, value) != true)) {
                    this._yt_etimeField = value;
                    this.RaisePropertyChanged("_yt_etime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yt_id {
            get {
                return this._yt_idField;
            }
            set {
                if ((this._yt_idField.Equals(value) != true)) {
                    this._yt_idField = value;
                    this.RaisePropertyChanged("_yt_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yt_state {
            get {
                return this._yt_stateField;
            }
            set {
                if ((this._yt_stateField.Equals(value) != true)) {
                    this._yt_stateField = value;
                    this.RaisePropertyChanged("_yt_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yt_userid {
            get {
                return this._yt_useridField;
            }
            set {
                if ((this._yt_useridField.Equals(value) != true)) {
                    this._yt_useridField = value;
                    this.RaisePropertyChanged("_yt_userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yt_week {
            get {
                return this._yt_weekField;
            }
            set {
                if ((object.ReferenceEquals(this._yt_weekField, value) != true)) {
                    this._yt_weekField = value;
                    this.RaisePropertyChanged("_yt_week");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YNT_YuyueNewThemEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.ReservationModel")]
    [System.SerializableAttribute()]
    public partial class YNT_YuyueNewThemEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _ynt_createpersonField;
        
        private System.DateTime _ynt_createtimeField;
        
        private string _ynt_describeField;
        
        private string _ynt_entryconditionField;
        
        private int _ynt_idField;
        
        private string _ynt_strField;
        
        private string _ynt_str2Field;
        
        private string _ynt_themnameField;
        
        private int _yt_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ynt_createperson {
            get {
                return this._ynt_createpersonField;
            }
            set {
                if ((object.ReferenceEquals(this._ynt_createpersonField, value) != true)) {
                    this._ynt_createpersonField = value;
                    this.RaisePropertyChanged("_ynt_createperson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _ynt_createtime {
            get {
                return this._ynt_createtimeField;
            }
            set {
                if ((this._ynt_createtimeField.Equals(value) != true)) {
                    this._ynt_createtimeField = value;
                    this.RaisePropertyChanged("_ynt_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ynt_describe {
            get {
                return this._ynt_describeField;
            }
            set {
                if ((object.ReferenceEquals(this._ynt_describeField, value) != true)) {
                    this._ynt_describeField = value;
                    this.RaisePropertyChanged("_ynt_describe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ynt_entrycondition {
            get {
                return this._ynt_entryconditionField;
            }
            set {
                if ((object.ReferenceEquals(this._ynt_entryconditionField, value) != true)) {
                    this._ynt_entryconditionField = value;
                    this.RaisePropertyChanged("_ynt_entrycondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ynt_id {
            get {
                return this._ynt_idField;
            }
            set {
                if ((this._ynt_idField.Equals(value) != true)) {
                    this._ynt_idField = value;
                    this.RaisePropertyChanged("_ynt_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ynt_str {
            get {
                return this._ynt_strField;
            }
            set {
                if ((object.ReferenceEquals(this._ynt_strField, value) != true)) {
                    this._ynt_strField = value;
                    this.RaisePropertyChanged("_ynt_str");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ynt_str2 {
            get {
                return this._ynt_str2Field;
            }
            set {
                if ((object.ReferenceEquals(this._ynt_str2Field, value) != true)) {
                    this._ynt_str2Field = value;
                    this.RaisePropertyChanged("_ynt_str2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ynt_themname {
            get {
                return this._ynt_themnameField;
            }
            set {
                if ((object.ReferenceEquals(this._ynt_themnameField, value) != true)) {
                    this._ynt_themnameField = value;
                    this.RaisePropertyChanged("_ynt_themname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yt_id {
            get {
                return this._yt_idField;
            }
            set {
                if ((this._yt_idField.Equals(value) != true)) {
                    this._yt_idField = value;
                    this.RaisePropertyChanged("_yt_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YOT_YuyueOldThemEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.ReservationModel")]
    [System.SerializableAttribute()]
    public partial class YOT_YuyueOldThemEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _ynt_idField;
        
        private string _yot_createpersonField;
        
        private System.DateTime _yot_createtimeField;
        
        private int _yot_idField;
        
        private string _yot_strField;
        
        private string _yot_str2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ynt_id {
            get {
                return this._ynt_idField;
            }
            set {
                if ((this._ynt_idField.Equals(value) != true)) {
                    this._ynt_idField = value;
                    this.RaisePropertyChanged("_ynt_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yot_createperson {
            get {
                return this._yot_createpersonField;
            }
            set {
                if ((object.ReferenceEquals(this._yot_createpersonField, value) != true)) {
                    this._yot_createpersonField = value;
                    this.RaisePropertyChanged("_yot_createperson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _yot_createtime {
            get {
                return this._yot_createtimeField;
            }
            set {
                if ((this._yot_createtimeField.Equals(value) != true)) {
                    this._yot_createtimeField = value;
                    this.RaisePropertyChanged("_yot_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yot_id {
            get {
                return this._yot_idField;
            }
            set {
                if ((this._yot_idField.Equals(value) != true)) {
                    this._yot_idField = value;
                    this.RaisePropertyChanged("_yot_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yot_str {
            get {
                return this._yot_strField;
            }
            set {
                if ((object.ReferenceEquals(this._yot_strField, value) != true)) {
                    this._yot_strField = value;
                    this.RaisePropertyChanged("_yot_str");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yot_str2 {
            get {
                return this._yot_str2Field;
            }
            set {
                if ((object.ReferenceEquals(this._yot_str2Field, value) != true)) {
                    this._yot_str2Field = value;
                    this.RaisePropertyChanged("_yot_str2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Y_UserYuYueEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.ReservationModel")]
    [System.SerializableAttribute()]
    public partial class Y_UserYuYueEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _yt_idField;
        
        private string _yu_createpersonField;
        
        private System.DateTime _yu_createtimeField;
        
        private System.DateTime _yu_dataField;
        
        private int _yu_deleteField;
        
        private int _yu_idField;
        
        private string _yu_qdescribeField;
        
        private int _yu_questiontypeField;
        
        private int _yu_stateField;
        
        private string _yu_strField;
        
        private string _yu_str2Field;
        
        private string _yu_timeField;
        
        private int _yu_useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yt_id {
            get {
                return this._yt_idField;
            }
            set {
                if ((this._yt_idField.Equals(value) != true)) {
                    this._yt_idField = value;
                    this.RaisePropertyChanged("_yt_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yu_createperson {
            get {
                return this._yu_createpersonField;
            }
            set {
                if ((object.ReferenceEquals(this._yu_createpersonField, value) != true)) {
                    this._yu_createpersonField = value;
                    this.RaisePropertyChanged("_yu_createperson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _yu_createtime {
            get {
                return this._yu_createtimeField;
            }
            set {
                if ((this._yu_createtimeField.Equals(value) != true)) {
                    this._yu_createtimeField = value;
                    this.RaisePropertyChanged("_yu_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _yu_data {
            get {
                return this._yu_dataField;
            }
            set {
                if ((this._yu_dataField.Equals(value) != true)) {
                    this._yu_dataField = value;
                    this.RaisePropertyChanged("_yu_data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yu_delete {
            get {
                return this._yu_deleteField;
            }
            set {
                if ((this._yu_deleteField.Equals(value) != true)) {
                    this._yu_deleteField = value;
                    this.RaisePropertyChanged("_yu_delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yu_id {
            get {
                return this._yu_idField;
            }
            set {
                if ((this._yu_idField.Equals(value) != true)) {
                    this._yu_idField = value;
                    this.RaisePropertyChanged("_yu_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yu_qdescribe {
            get {
                return this._yu_qdescribeField;
            }
            set {
                if ((object.ReferenceEquals(this._yu_qdescribeField, value) != true)) {
                    this._yu_qdescribeField = value;
                    this.RaisePropertyChanged("_yu_qdescribe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yu_questiontype {
            get {
                return this._yu_questiontypeField;
            }
            set {
                if ((this._yu_questiontypeField.Equals(value) != true)) {
                    this._yu_questiontypeField = value;
                    this.RaisePropertyChanged("_yu_questiontype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yu_state {
            get {
                return this._yu_stateField;
            }
            set {
                if ((this._yu_stateField.Equals(value) != true)) {
                    this._yu_stateField = value;
                    this.RaisePropertyChanged("_yu_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yu_str {
            get {
                return this._yu_strField;
            }
            set {
                if ((object.ReferenceEquals(this._yu_strField, value) != true)) {
                    this._yu_strField = value;
                    this.RaisePropertyChanged("_yu_str");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yu_str2 {
            get {
                return this._yu_str2Field;
            }
            set {
                if ((object.ReferenceEquals(this._yu_str2Field, value) != true)) {
                    this._yu_str2Field = value;
                    this.RaisePropertyChanged("_yu_str2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _yu_time {
            get {
                return this._yu_timeField;
            }
            set {
                if ((object.ReferenceEquals(this._yu_timeField, value) != true)) {
                    this._yu_timeField = value;
                    this.RaisePropertyChanged("_yu_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _yu_userid {
            get {
                return this._yu_useridField;
            }
            set {
                if ((this._yu_useridField.Equals(value) != true)) {
                    this._yu_useridField = value;
                    this.RaisePropertyChanged("_yu_userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationService.IReservationService")]
    public interface IReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/Insert", ReplyAction="http://tempuri.org/IReservationService/InsertResponse")]
        long Insert(WebPages.ReservationService.YT_YuYueTimeEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/YNTInsert", ReplyAction="http://tempuri.org/IReservationService/YNTInsertResponse")]
        long YNTInsert(WebPages.ReservationService.YNT_YuyueNewThemEntity model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/YOTInsert", ReplyAction="http://tempuri.org/IReservationService/YOTInsertResponse")]
        long YOTInsert(WebPages.ReservationService.YOT_YuyueOldThemEntity model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetYNTThem", ReplyAction="http://tempuri.org/IReservationService/GetYNTThemResponse")]
        System.Data.DataTable GetYNTThem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetYNTInfoByID", ReplyAction="http://tempuri.org/IReservationService/GetYNTInfoByIDResponse")]
        WebPages.ReservationService.YNT_YuyueNewThemEntity GetYNTInfoByID(int YNT_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetYTTemp", ReplyAction="http://tempuri.org/IReservationService/GetYTTempResponse")]
        System.Data.DataSet GetYTTemp(int UserID, int StarPageIndex, int EndPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetEntity", ReplyAction="http://tempuri.org/IReservationService/GetEntityResponse")]
        WebPages.ReservationService.Y_UserYuYueEntity GetEntity(int YU_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetEntityBYID", ReplyAction="http://tempuri.org/IReservationService/GetEntityBYIDResponse")]
        WebPages.ReservationService.Y_UserYuYueEntity GetEntityBYID(int YT_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationServiceChannel : WebPages.ReservationService.IReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<WebPages.ReservationService.IReservationService>, WebPages.ReservationService.IReservationService {
        
        public ReservationServiceClient() {
        }
        
        public ReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long Insert(WebPages.ReservationService.YT_YuYueTimeEntity entityInfo) {
            return base.Channel.Insert(entityInfo);
        }
        
        public long YNTInsert(WebPages.ReservationService.YNT_YuyueNewThemEntity model) {
            return base.Channel.YNTInsert(model);
        }
        
        public long YOTInsert(WebPages.ReservationService.YOT_YuyueOldThemEntity model) {
            return base.Channel.YOTInsert(model);
        }
        
        public System.Data.DataTable GetYNTThem() {
            return base.Channel.GetYNTThem();
        }
        
        public WebPages.ReservationService.YNT_YuyueNewThemEntity GetYNTInfoByID(int YNT_ID) {
            return base.Channel.GetYNTInfoByID(YNT_ID);
        }
        
        public System.Data.DataSet GetYTTemp(int UserID, int StarPageIndex, int EndPageIndex) {
            return base.Channel.GetYTTemp(UserID, StarPageIndex, EndPageIndex);
        }
        
        public WebPages.ReservationService.Y_UserYuYueEntity GetEntity(int YU_ID) {
            return base.Channel.GetEntity(YU_ID);
        }
        
        public WebPages.ReservationService.Y_UserYuYueEntity GetEntityBYID(int YT_ID) {
            return base.Channel.GetEntityBYID(YT_ID);
        }
    }
}
