//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.DistributeRecordService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amount_InfoEntity", Namespace="http://schemas.datacontract.org/2004/07/JSBR.Model.BaseTable.Entity")]
    [System.SerializableAttribute()]
    public partial class Amount_InfoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _amount_codeField;
        
        private string _amount_displaynameField;
        
        private string _amount_guidanceField;
        
        private long _amount_idField;
        
        private string _amount_jianpinField;
        
        private string _amount_marksField;
        
        private string _amount_nameField;
        
        private string _amount_pinyinField;
        
        private int _amount_sourceField;
        
        private int _amount_subjectnumField;
        
        private long _amount_typeidField;
        
        private decimal _completeamountField;
        
        private System.DateTime _createtimeField;
        
        private string _end_applypeoplesField;
        
        private int _is_deleteField;
        
        private string _start_applypeoplesField;
        
        private int _u_idField;
        
        private int amountCreatePersonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_code {
            get {
                return this._amount_codeField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_codeField, value) != true)) {
                    this._amount_codeField = value;
                    this.RaisePropertyChanged("_amount_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_displayname {
            get {
                return this._amount_displaynameField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_displaynameField, value) != true)) {
                    this._amount_displaynameField = value;
                    this.RaisePropertyChanged("_amount_displayname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_guidance {
            get {
                return this._amount_guidanceField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_guidanceField, value) != true)) {
                    this._amount_guidanceField = value;
                    this.RaisePropertyChanged("_amount_guidance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _amount_id {
            get {
                return this._amount_idField;
            }
            set {
                if ((this._amount_idField.Equals(value) != true)) {
                    this._amount_idField = value;
                    this.RaisePropertyChanged("_amount_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_jianpin {
            get {
                return this._amount_jianpinField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_jianpinField, value) != true)) {
                    this._amount_jianpinField = value;
                    this.RaisePropertyChanged("_amount_jianpin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_marks {
            get {
                return this._amount_marksField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_marksField, value) != true)) {
                    this._amount_marksField = value;
                    this.RaisePropertyChanged("_amount_marks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_name {
            get {
                return this._amount_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_nameField, value) != true)) {
                    this._amount_nameField = value;
                    this.RaisePropertyChanged("_amount_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_pinyin {
            get {
                return this._amount_pinyinField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_pinyinField, value) != true)) {
                    this._amount_pinyinField = value;
                    this.RaisePropertyChanged("_amount_pinyin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _amount_source {
            get {
                return this._amount_sourceField;
            }
            set {
                if ((this._amount_sourceField.Equals(value) != true)) {
                    this._amount_sourceField = value;
                    this.RaisePropertyChanged("_amount_source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _amount_subjectnum {
            get {
                return this._amount_subjectnumField;
            }
            set {
                if ((this._amount_subjectnumField.Equals(value) != true)) {
                    this._amount_subjectnumField = value;
                    this.RaisePropertyChanged("_amount_subjectnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _amount_typeid {
            get {
                return this._amount_typeidField;
            }
            set {
                if ((this._amount_typeidField.Equals(value) != true)) {
                    this._amount_typeidField = value;
                    this.RaisePropertyChanged("_amount_typeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _completeamount {
            get {
                return this._completeamountField;
            }
            set {
                if ((this._completeamountField.Equals(value) != true)) {
                    this._completeamountField = value;
                    this.RaisePropertyChanged("_completeamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createtime {
            get {
                return this._createtimeField;
            }
            set {
                if ((this._createtimeField.Equals(value) != true)) {
                    this._createtimeField = value;
                    this.RaisePropertyChanged("_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _end_applypeoples {
            get {
                return this._end_applypeoplesField;
            }
            set {
                if ((object.ReferenceEquals(this._end_applypeoplesField, value) != true)) {
                    this._end_applypeoplesField = value;
                    this.RaisePropertyChanged("_end_applypeoples");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _is_delete {
            get {
                return this._is_deleteField;
            }
            set {
                if ((this._is_deleteField.Equals(value) != true)) {
                    this._is_deleteField = value;
                    this.RaisePropertyChanged("_is_delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _start_applypeoples {
            get {
                return this._start_applypeoplesField;
            }
            set {
                if ((object.ReferenceEquals(this._start_applypeoplesField, value) != true)) {
                    this._start_applypeoplesField = value;
                    this.RaisePropertyChanged("_start_applypeoples");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _u_id {
            get {
                return this._u_idField;
            }
            set {
                if ((this._u_idField.Equals(value) != true)) {
                    this._u_idField = value;
                    this.RaisePropertyChanged("_u_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int amountCreatePerson {
            get {
                return this.amountCreatePersonField;
            }
            set {
                if ((this.amountCreatePersonField.Equals(value) != true)) {
                    this.amountCreatePersonField = value;
                    this.RaisePropertyChanged("amountCreatePerson");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerAddEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.DistributeRecordModel")]
    [System.SerializableAttribute()]
    public partial class AnswerAddEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _amount_codeField;
        
        private System.DateTime _answer_createtimeField;
        
        private System.DateTime _answer_starttimerField;
        
        private int _answer_stateField;
        
        private string _answeradd_codeField;
        
        private int _answeradd_idField;
        
        private string _answeradd_recordField;
        
        private int _answeradd_scoreField;
        
        private string _answeralltimeField;
        
        private int _answerisdeleteField;
        
        private string _answerpeopleField;
        
        private string _distriidField;
        
        private string _newansweraddrecordField;
        
        private int _u_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_code {
            get {
                return this._amount_codeField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_codeField, value) != true)) {
                    this._amount_codeField = value;
                    this.RaisePropertyChanged("_amount_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _answer_createtime {
            get {
                return this._answer_createtimeField;
            }
            set {
                if ((this._answer_createtimeField.Equals(value) != true)) {
                    this._answer_createtimeField = value;
                    this.RaisePropertyChanged("_answer_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _answer_starttimer {
            get {
                return this._answer_starttimerField;
            }
            set {
                if ((this._answer_starttimerField.Equals(value) != true)) {
                    this._answer_starttimerField = value;
                    this.RaisePropertyChanged("_answer_starttimer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answer_state {
            get {
                return this._answer_stateField;
            }
            set {
                if ((this._answer_stateField.Equals(value) != true)) {
                    this._answer_stateField = value;
                    this.RaisePropertyChanged("_answer_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _answeradd_code {
            get {
                return this._answeradd_codeField;
            }
            set {
                if ((object.ReferenceEquals(this._answeradd_codeField, value) != true)) {
                    this._answeradd_codeField = value;
                    this.RaisePropertyChanged("_answeradd_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answeradd_id {
            get {
                return this._answeradd_idField;
            }
            set {
                if ((this._answeradd_idField.Equals(value) != true)) {
                    this._answeradd_idField = value;
                    this.RaisePropertyChanged("_answeradd_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _answeradd_record {
            get {
                return this._answeradd_recordField;
            }
            set {
                if ((object.ReferenceEquals(this._answeradd_recordField, value) != true)) {
                    this._answeradd_recordField = value;
                    this.RaisePropertyChanged("_answeradd_record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answeradd_score {
            get {
                return this._answeradd_scoreField;
            }
            set {
                if ((this._answeradd_scoreField.Equals(value) != true)) {
                    this._answeradd_scoreField = value;
                    this.RaisePropertyChanged("_answeradd_score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _answeralltime {
            get {
                return this._answeralltimeField;
            }
            set {
                if ((object.ReferenceEquals(this._answeralltimeField, value) != true)) {
                    this._answeralltimeField = value;
                    this.RaisePropertyChanged("_answeralltime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answerisdelete {
            get {
                return this._answerisdeleteField;
            }
            set {
                if ((this._answerisdeleteField.Equals(value) != true)) {
                    this._answerisdeleteField = value;
                    this.RaisePropertyChanged("_answerisdelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _answerpeople {
            get {
                return this._answerpeopleField;
            }
            set {
                if ((object.ReferenceEquals(this._answerpeopleField, value) != true)) {
                    this._answerpeopleField = value;
                    this.RaisePropertyChanged("_answerpeople");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _distriid {
            get {
                return this._distriidField;
            }
            set {
                if ((object.ReferenceEquals(this._distriidField, value) != true)) {
                    this._distriidField = value;
                    this.RaisePropertyChanged("_distriid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _newansweraddrecord {
            get {
                return this._newansweraddrecordField;
            }
            set {
                if ((object.ReferenceEquals(this._newansweraddrecordField, value) != true)) {
                    this._newansweraddrecordField = value;
                    this.RaisePropertyChanged("_newansweraddrecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _u_id {
            get {
                return this._u_idField;
            }
            set {
                if ((this._u_idField.Equals(value) != true)) {
                    this._u_idField = value;
                    this.RaisePropertyChanged("_u_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributionSetEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.DistributeRecordModel")]
    [System.SerializableAttribute()]
    public partial class DistributionSetEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _answerendtimeField;
        
        private System.Nullable<System.DateTime> _answerstarttimeField;
        
        private System.DateTime _createtimeField;
        
        private string _distributionnameField;
        
        private long _distributionsetidField;
        
        private int _is_againField;
        
        private int _is_noticeField;
        
        private int _is_presentField;
        
        private int _is_seereportField;
        
        private string _sendcontentField;
        
        private long _u_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _answerendtime {
            get {
                return this._answerendtimeField;
            }
            set {
                if ((this._answerendtimeField.Equals(value) != true)) {
                    this._answerendtimeField = value;
                    this.RaisePropertyChanged("_answerendtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _answerstarttime {
            get {
                return this._answerstarttimeField;
            }
            set {
                if ((this._answerstarttimeField.Equals(value) != true)) {
                    this._answerstarttimeField = value;
                    this.RaisePropertyChanged("_answerstarttime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createtime {
            get {
                return this._createtimeField;
            }
            set {
                if ((this._createtimeField.Equals(value) != true)) {
                    this._createtimeField = value;
                    this.RaisePropertyChanged("_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _distributionname {
            get {
                return this._distributionnameField;
            }
            set {
                if ((object.ReferenceEquals(this._distributionnameField, value) != true)) {
                    this._distributionnameField = value;
                    this.RaisePropertyChanged("_distributionname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _distributionsetid {
            get {
                return this._distributionsetidField;
            }
            set {
                if ((this._distributionsetidField.Equals(value) != true)) {
                    this._distributionsetidField = value;
                    this.RaisePropertyChanged("_distributionsetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _is_again {
            get {
                return this._is_againField;
            }
            set {
                if ((this._is_againField.Equals(value) != true)) {
                    this._is_againField = value;
                    this.RaisePropertyChanged("_is_again");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _is_notice {
            get {
                return this._is_noticeField;
            }
            set {
                if ((this._is_noticeField.Equals(value) != true)) {
                    this._is_noticeField = value;
                    this.RaisePropertyChanged("_is_notice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _is_present {
            get {
                return this._is_presentField;
            }
            set {
                if ((this._is_presentField.Equals(value) != true)) {
                    this._is_presentField = value;
                    this.RaisePropertyChanged("_is_present");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _is_seereport {
            get {
                return this._is_seereportField;
            }
            set {
                if ((this._is_seereportField.Equals(value) != true)) {
                    this._is_seereportField = value;
                    this.RaisePropertyChanged("_is_seereport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _sendcontent {
            get {
                return this._sendcontentField;
            }
            set {
                if ((object.ReferenceEquals(this._sendcontentField, value) != true)) {
                    this._sendcontentField = value;
                    this.RaisePropertyChanged("_sendcontent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _u_id {
            get {
                return this._u_idField;
            }
            set {
                if ((this._u_idField.Equals(value) != true)) {
                    this._u_idField = value;
                    this.RaisePropertyChanged("_u_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amount_Distribution_RelationEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.DistributeRecordModel")]
    [System.SerializableAttribute()]
    public partial class Amount_Distribution_RelationEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long _a_dis_idField;
        
        private string _amount_codeField;
        
        private System.DateTime _createtimeField;
        
        private long _distributionsetidField;
        
        private long _disuidField;
        
        private int _u_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _a_dis_id {
            get {
                return this._a_dis_idField;
            }
            set {
                if ((this._a_dis_idField.Equals(value) != true)) {
                    this._a_dis_idField = value;
                    this.RaisePropertyChanged("_a_dis_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _amount_code {
            get {
                return this._amount_codeField;
            }
            set {
                if ((object.ReferenceEquals(this._amount_codeField, value) != true)) {
                    this._amount_codeField = value;
                    this.RaisePropertyChanged("_amount_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createtime {
            get {
                return this._createtimeField;
            }
            set {
                if ((this._createtimeField.Equals(value) != true)) {
                    this._createtimeField = value;
                    this.RaisePropertyChanged("_createtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _distributionsetid {
            get {
                return this._distributionsetidField;
            }
            set {
                if ((this._distributionsetidField.Equals(value) != true)) {
                    this._distributionsetidField = value;
                    this.RaisePropertyChanged("_distributionsetid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _disuid {
            get {
                return this._disuidField;
            }
            set {
                if ((this._disuidField.Equals(value) != true)) {
                    this._disuidField = value;
                    this.RaisePropertyChanged("_disuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _u_id {
            get {
                return this._u_idField;
            }
            set {
                if ((this._u_idField.Equals(value) != true)) {
                    this._u_idField = value;
                    this.RaisePropertyChanged("_u_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Questionnaire_Distribution_RelationEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.DistributeRecordModel")]
    [System.SerializableAttribute()]
    public partial class Questionnaire_Distribution_RelationEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _codeField;
        
        private System.DateTime _createTimeField;
        
        private string _disUIdField;
        
        private bool _is_AnonymityField;
        
        private bool _is_DeleteField;
        
        private string _qCodeField;
        
        private long _uIdField;
        
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _code {
            get {
                return this._codeField;
            }
            set {
                if ((object.ReferenceEquals(this._codeField, value) != true)) {
                    this._codeField = value;
                    this.RaisePropertyChanged("_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createTime {
            get {
                return this._createTimeField;
            }
            set {
                if ((this._createTimeField.Equals(value) != true)) {
                    this._createTimeField = value;
                    this.RaisePropertyChanged("_createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _disUId {
            get {
                return this._disUIdField;
            }
            set {
                if ((object.ReferenceEquals(this._disUIdField, value) != true)) {
                    this._disUIdField = value;
                    this.RaisePropertyChanged("_disUId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _is_Anonymity {
            get {
                return this._is_AnonymityField;
            }
            set {
                if ((this._is_AnonymityField.Equals(value) != true)) {
                    this._is_AnonymityField = value;
                    this.RaisePropertyChanged("_is_Anonymity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _is_Delete {
            get {
                return this._is_DeleteField;
            }
            set {
                if ((this._is_DeleteField.Equals(value) != true)) {
                    this._is_DeleteField = value;
                    this.RaisePropertyChanged("_is_Delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _qCode {
            get {
                return this._qCodeField;
            }
            set {
                if ((object.ReferenceEquals(this._qCodeField, value) != true)) {
                    this._qCodeField = value;
                    this.RaisePropertyChanged("_qCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _uId {
            get {
                return this._uIdField;
            }
            set {
                if ((this._uIdField.Equals(value) != true)) {
                    this._uIdField = value;
                    this.RaisePropertyChanged("_uId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="R_ReportEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.R_ReportEntity")]
    [System.SerializableAttribute()]
    public partial class R_ReportEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _answeidField;
        
        private int _createuidField;
        
        private string _r_codeField;
        
        private System.DateTime _r_createdateField;
        
        private int _r_idField;
        
        private string _reportjsonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answeid {
            get {
                return this._answeidField;
            }
            set {
                if ((this._answeidField.Equals(value) != true)) {
                    this._answeidField = value;
                    this.RaisePropertyChanged("_answeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _createuid {
            get {
                return this._createuidField;
            }
            set {
                if ((this._createuidField.Equals(value) != true)) {
                    this._createuidField = value;
                    this.RaisePropertyChanged("_createuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _r_code {
            get {
                return this._r_codeField;
            }
            set {
                if ((object.ReferenceEquals(this._r_codeField, value) != true)) {
                    this._r_codeField = value;
                    this.RaisePropertyChanged("_r_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _r_createdate {
            get {
                return this._r_createdateField;
            }
            set {
                if ((this._r_createdateField.Equals(value) != true)) {
                    this._r_createdateField = value;
                    this.RaisePropertyChanged("_r_createdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _r_id {
            get {
                return this._r_idField;
            }
            set {
                if ((this._r_idField.Equals(value) != true)) {
                    this._r_idField = value;
                    this.RaisePropertyChanged("_r_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _reportjson {
            get {
                return this._reportjsonField;
            }
            set {
                if ((object.ReferenceEquals(this._reportjsonField, value) != true)) {
                    this._reportjsonField = value;
                    this.RaisePropertyChanged("_reportjson");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.BasicSettingModel")]
    [System.SerializableAttribute()]
    public partial class State : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SucessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fail {
            get {
                return this.FailField;
            }
            set {
                if ((this.FailField.Equals(value) != true)) {
                    this.FailField = value;
                    this.RaisePropertyChanged("Fail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailName {
            get {
                return this.FailNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FailNameField, value) != true)) {
                    this.FailNameField = value;
                    this.RaisePropertyChanged("FailName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sucess {
            get {
                return this.SucessField;
            }
            set {
                if ((this.SucessField.Equals(value) != true)) {
                    this.SucessField = value;
                    this.RaisePropertyChanged("Sucess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialReport.Report", Namespace="http://schemas.datacontract.org/2004/07/EntieyBLL")]
    [System.SerializableAttribute()]
    public partial class SpecialReportReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebPages.DistributeRecordService.SpecialReportReport.DimensionEntity> DimensionEntitysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WebPages.DistributeRecordService.SpecialReportReport.UserInfo> UserINfosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebPages.DistributeRecordService.SpecialReportReport.DimensionEntity> DimensionEntitys {
            get {
                return this.DimensionEntitysField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionEntitysField, value) != true)) {
                    this.DimensionEntitysField = value;
                    this.RaisePropertyChanged("DimensionEntitys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WebPages.DistributeRecordService.SpecialReportReport.UserInfo> UserINfos {
            get {
                return this.UserINfosField;
            }
            set {
                if ((object.ReferenceEquals(this.UserINfosField, value) != true)) {
                    this.UserINfosField = value;
                    this.RaisePropertyChanged("UserINfos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="SpecialReport.Report.DimensionEntity", Namespace="http://schemas.datacontract.org/2004/07/EntieyBLL")]
        [System.SerializableAttribute()]
        public partial class DimensionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ANameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AcodesField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ConversionFormulaField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double ConversionScoreField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string D_CodeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FormulasField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RdeorField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double ScoreField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string WD_NameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string _NormNameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int scoretypeField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AName {
                get {
                    return this.ANameField;
                }
                set {
                    if ((object.ReferenceEquals(this.ANameField, value) != true)) {
                        this.ANameField = value;
                        this.RaisePropertyChanged("AName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Acodes {
                get {
                    return this.AcodesField;
                }
                set {
                    if ((object.ReferenceEquals(this.AcodesField, value) != true)) {
                        this.AcodesField = value;
                        this.RaisePropertyChanged("Acodes");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ConversionFormula {
                get {
                    return this.ConversionFormulaField;
                }
                set {
                    if ((object.ReferenceEquals(this.ConversionFormulaField, value) != true)) {
                        this.ConversionFormulaField = value;
                        this.RaisePropertyChanged("ConversionFormula");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double ConversionScore {
                get {
                    return this.ConversionScoreField;
                }
                set {
                    if ((this.ConversionScoreField.Equals(value) != true)) {
                        this.ConversionScoreField = value;
                        this.RaisePropertyChanged("ConversionScore");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string D_Code {
                get {
                    return this.D_CodeField;
                }
                set {
                    if ((object.ReferenceEquals(this.D_CodeField, value) != true)) {
                        this.D_CodeField = value;
                        this.RaisePropertyChanged("D_Code");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Formulas {
                get {
                    return this.FormulasField;
                }
                set {
                    if ((object.ReferenceEquals(this.FormulasField, value) != true)) {
                        this.FormulasField = value;
                        this.RaisePropertyChanged("Formulas");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Rdeor {
                get {
                    return this.RdeorField;
                }
                set {
                    if ((object.ReferenceEquals(this.RdeorField, value) != true)) {
                        this.RdeorField = value;
                        this.RaisePropertyChanged("Rdeor");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double Score {
                get {
                    return this.ScoreField;
                }
                set {
                    if ((this.ScoreField.Equals(value) != true)) {
                        this.ScoreField = value;
                        this.RaisePropertyChanged("Score");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string WD_Name {
                get {
                    return this.WD_NameField;
                }
                set {
                    if ((object.ReferenceEquals(this.WD_NameField, value) != true)) {
                        this.WD_NameField = value;
                        this.RaisePropertyChanged("WD_Name");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string _NormName {
                get {
                    return this._NormNameField;
                }
                set {
                    if ((object.ReferenceEquals(this._NormNameField, value) != true)) {
                        this._NormNameField = value;
                        this.RaisePropertyChanged("_NormName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int scoretype {
                get {
                    return this.scoretypeField;
                }
                set {
                    if ((this.scoretypeField.Equals(value) != true)) {
                        this.scoretypeField = value;
                        this.RaisePropertyChanged("scoretype");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="SpecialReport.Report.UserInfo", Namespace="http://schemas.datacontract.org/2004/07/EntieyBLL")]
        [System.SerializableAttribute()]
        public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AnswerRecordField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double MaxValueField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double MinValueField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AnswerRecord {
                get {
                    return this.AnswerRecordField;
                }
                set {
                    if ((object.ReferenceEquals(this.AnswerRecordField, value) != true)) {
                        this.AnswerRecordField = value;
                        this.RaisePropertyChanged("AnswerRecord");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double MaxValue {
                get {
                    return this.MaxValueField;
                }
                set {
                    if ((this.MaxValueField.Equals(value) != true)) {
                        this.MaxValueField = value;
                        this.RaisePropertyChanged("MaxValue");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double MinValue {
                get {
                    return this.MinValueField;
                }
                set {
                    if ((this.MinValueField.Equals(value) != true)) {
                        this.MinValueField = value;
                        this.RaisePropertyChanged("MinValue");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistributeRecordService.IDistributeRecordService")]
    public interface IDistributeRecordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/InitiDistributeRecordTable", ReplyAction="http://tempuri.org/IDistributeRecordService/InitiDistributeRecordTableResponse")]
        System.Data.DataSet InitiDistributeRecordTable(int userID, int amountID, string loginName, int departmentID, System.Nullable<System.DateTime> distriStartTime, System.Nullable<System.DateTime> distriEndTime, int ansID, int StarPageIndex, int EndPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/BeforDelete", ReplyAction="http://tempuri.org/IDistributeRecordService/BeforDeleteResponse")]
        bool BeforDelete(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/DeleteDistributeRecord", ReplyAction="http://tempuri.org/IDistributeRecordService/DeleteDistributeRecordResponse")]
        bool DeleteDistributeRecord(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetMytestTable", ReplyAction="http://tempuri.org/IDistributeRecordService/GetMytestTableResponse")]
        System.Data.DataSet GetMytestTable(int UserID, int StarPageIndex, int EndPageIndex, string GaugeName, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetAEntity", ReplyAction="http://tempuri.org/IDistributeRecordService/GetAEntityResponse")]
        WebPages.DistributeRecordService.Amount_InfoEntity GetAEntity(string Amount_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetSubject", ReplyAction="http://tempuri.org/IDistributeRecordService/GetSubjectResponse")]
        System.Data.DataTable GetSubject(string Acode, int ARadom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetProblem", ReplyAction="http://tempuri.org/IDistributeRecordService/GetProblemResponse")]
        System.Data.DataTable GetProblem(string Acode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/Insert", ReplyAction="http://tempuri.org/IDistributeRecordService/InsertResponse")]
        long Insert(WebPages.DistributeRecordService.AnswerAddEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetAnswerAddEntity", ReplyAction="http://tempuri.org/IDistributeRecordService/GetAnswerAddEntityResponse")]
        WebPages.DistributeRecordService.AnswerAddEntity GetAnswerAddEntity(int AnswerAddID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetAnswerAddEntity_ByDID", ReplyAction="http://tempuri.org/IDistributeRecordService/GetAnswerAddEntity_ByDIDResponse")]
        WebPages.DistributeRecordService.AnswerAddEntity GetAnswerAddEntity_ByDID(int DID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/Update", ReplyAction="http://tempuri.org/IDistributeRecordService/UpdateResponse")]
        bool Update(WebPages.DistributeRecordService.AnswerAddEntity AnswerModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/DeleteAnswer", ReplyAction="http://tempuri.org/IDistributeRecordService/DeleteAnswerResponse")]
        bool DeleteAnswer(int AnswerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetEvaluationTable", ReplyAction="http://tempuri.org/IDistributeRecordService/GetEvaluationTableResponse")]
        System.Data.DataSet GetEvaluationTable(string UName, int StarPageIndex, int EndPageIndex, string loginName, string AName, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetViewFiles", ReplyAction="http://tempuri.org/IDistributeRecordService/GetViewFilesResponse")]
        System.Data.DataSet GetViewFiles(string LoginName, string Amount_Code, string EnterpriseCode, int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetDistrubuteUserInfo", ReplyAction="http://tempuri.org/IDistributeRecordService/GetDistrubuteUserInfoResponse")]
        System.Data.DataSet GetDistrubuteUserInfo(string loginName, int StarPageIndex, int EndPageIndex, int UID, string EnterpriseCode, int departmentID, int Sel_RoleType, string user_infos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/InsertDistributionSet", ReplyAction="http://tempuri.org/IDistributeRecordService/InsertDistributionSetResponse")]
        long InsertDistributionSet(WebPages.DistributeRecordService.DistributionSetEntity model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/AInsert", ReplyAction="http://tempuri.org/IDistributeRecordService/AInsertResponse")]
        long AInsert(WebPages.DistributeRecordService.Amount_Distribution_RelationEntity Amodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/QInsert", ReplyAction="http://tempuri.org/IDistributeRecordService/QInsertResponse")]
        long QInsert(WebPages.DistributeRecordService.Questionnaire_Distribution_RelationEntity Qmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/Amount_deletes", ReplyAction="http://tempuri.org/IDistributeRecordService/Amount_deletesResponse")]
        bool Amount_deletes(string chenum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetCount", ReplyAction="http://tempuri.org/IDistributeRecordService/GetCountResponse")]
        long GetCount(string Acode, int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/Answer", ReplyAction="http://tempuri.org/IDistributeRecordService/AnswerResponse")]
        bool Answer(string AnswerRecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetOperationTemp", ReplyAction="http://tempuri.org/IDistributeRecordService/GetOperationTempResponse")]
        System.Data.DataTable GetOperationTemp(string SubCodeStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetOperationCodeTemp", ReplyAction="http://tempuri.org/IDistributeRecordService/GetOperationCodeTempResponse")]
        System.Data.DataTable GetOperationCodeTemp(string SubCodeStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/InsetsAnswerPTwo", ReplyAction="http://tempuri.org/IDistributeRecordService/InsetsAnswerPTwoResponse")]
        long InsetsAnswerPTwo(WebPages.DistributeRecordService.AnswerAddEntity entityInfo, WebPages.DistributeRecordService.R_ReportEntity entityInfos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetDistrubuteIsDelete", ReplyAction="http://tempuri.org/IDistributeRecordService/GetDistrubuteIsDeleteResponse")]
        bool GetDistrubuteIsDelete(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/BulkInsert", ReplyAction="http://tempuri.org/IDistributeRecordService/BulkInsertResponse")]
        WebPages.DistributeRecordService.State BulkInsert(System.Collections.Generic.List<string> AcodeArray, System.Collections.Generic.List<string> UserArray, int DID, int CreatPepleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetScoreHtml", ReplyAction="http://tempuri.org/IDistributeRecordService/GetScoreHtmlResponse")]
        string GetScoreHtml(WebPages.DistributeRecordService.SpecialReportReport lr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistributeRecordService/GetScoreHtmlS", ReplyAction="http://tempuri.org/IDistributeRecordService/GetScoreHtmlSResponse")]
        string GetScoreHtmlS(WebPages.DistributeRecordService.SpecialReportReport lr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistributeRecordServiceChannel : WebPages.DistributeRecordService.IDistributeRecordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributeRecordServiceClient : System.ServiceModel.ClientBase<WebPages.DistributeRecordService.IDistributeRecordService>, WebPages.DistributeRecordService.IDistributeRecordService {
        
        public DistributeRecordServiceClient() {
        }
        
        public DistributeRecordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributeRecordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributeRecordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributeRecordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet InitiDistributeRecordTable(int userID, int amountID, string loginName, int departmentID, System.Nullable<System.DateTime> distriStartTime, System.Nullable<System.DateTime> distriEndTime, int ansID, int StarPageIndex, int EndPageIndex) {
            return base.Channel.InitiDistributeRecordTable(userID, amountID, loginName, departmentID, distriStartTime, distriEndTime, ansID, StarPageIndex, EndPageIndex);
        }
        
        public bool BeforDelete(int distriID) {
            return base.Channel.BeforDelete(distriID);
        }
        
        public bool DeleteDistributeRecord(int distriID) {
            return base.Channel.DeleteDistributeRecord(distriID);
        }
        
        public System.Data.DataSet GetMytestTable(int UserID, int StarPageIndex, int EndPageIndex, string GaugeName, string EnterpriseCode) {
            return base.Channel.GetMytestTable(UserID, StarPageIndex, EndPageIndex, GaugeName, EnterpriseCode);
        }
        
        public WebPages.DistributeRecordService.Amount_InfoEntity GetAEntity(string Amount_Code) {
            return base.Channel.GetAEntity(Amount_Code);
        }
        
        public System.Data.DataTable GetSubject(string Acode, int ARadom) {
            return base.Channel.GetSubject(Acode, ARadom);
        }
        
        public System.Data.DataTable GetProblem(string Acode) {
            return base.Channel.GetProblem(Acode);
        }
        
        public long Insert(WebPages.DistributeRecordService.AnswerAddEntity entityInfo) {
            return base.Channel.Insert(entityInfo);
        }
        
        public WebPages.DistributeRecordService.AnswerAddEntity GetAnswerAddEntity(int AnswerAddID) {
            return base.Channel.GetAnswerAddEntity(AnswerAddID);
        }
        
        public WebPages.DistributeRecordService.AnswerAddEntity GetAnswerAddEntity_ByDID(int DID) {
            return base.Channel.GetAnswerAddEntity_ByDID(DID);
        }
        
        public bool Update(WebPages.DistributeRecordService.AnswerAddEntity AnswerModel) {
            return base.Channel.Update(AnswerModel);
        }
        
        public bool DeleteAnswer(int AnswerID) {
            return base.Channel.DeleteAnswer(AnswerID);
        }
        
        public System.Data.DataSet GetEvaluationTable(string UName, int StarPageIndex, int EndPageIndex, string loginName, string AName, string EnterpriseCode) {
            return base.Channel.GetEvaluationTable(UName, StarPageIndex, EndPageIndex, loginName, AName, EnterpriseCode);
        }
        
        public System.Data.DataSet GetViewFiles(string LoginName, string Amount_Code, string EnterpriseCode, int U_ID) {
            return base.Channel.GetViewFiles(LoginName, Amount_Code, EnterpriseCode, U_ID);
        }
        
        public System.Data.DataSet GetDistrubuteUserInfo(string loginName, int StarPageIndex, int EndPageIndex, int UID, string EnterpriseCode, int departmentID, int Sel_RoleType, string user_infos) {
            return base.Channel.GetDistrubuteUserInfo(loginName, StarPageIndex, EndPageIndex, UID, EnterpriseCode, departmentID, Sel_RoleType, user_infos);
        }
        
        public long InsertDistributionSet(WebPages.DistributeRecordService.DistributionSetEntity model) {
            return base.Channel.InsertDistributionSet(model);
        }
        
        public long AInsert(WebPages.DistributeRecordService.Amount_Distribution_RelationEntity Amodel) {
            return base.Channel.AInsert(Amodel);
        }
        
        public long QInsert(WebPages.DistributeRecordService.Questionnaire_Distribution_RelationEntity Qmodel) {
            return base.Channel.QInsert(Qmodel);
        }
        
        public bool Amount_deletes(string chenum) {
            return base.Channel.Amount_deletes(chenum);
        }
        
        public long GetCount(string Acode, int U_ID) {
            return base.Channel.GetCount(Acode, U_ID);
        }
        
        public bool Answer(string AnswerRecode) {
            return base.Channel.Answer(AnswerRecode);
        }
        
        public System.Data.DataTable GetOperationTemp(string SubCodeStr) {
            return base.Channel.GetOperationTemp(SubCodeStr);
        }
        
        public System.Data.DataTable GetOperationCodeTemp(string SubCodeStr) {
            return base.Channel.GetOperationCodeTemp(SubCodeStr);
        }
        
        public long InsetsAnswerPTwo(WebPages.DistributeRecordService.AnswerAddEntity entityInfo, WebPages.DistributeRecordService.R_ReportEntity entityInfos) {
            return base.Channel.InsetsAnswerPTwo(entityInfo, entityInfos);
        }
        
        public bool GetDistrubuteIsDelete(int distriID) {
            return base.Channel.GetDistrubuteIsDelete(distriID);
        }
        
        public WebPages.DistributeRecordService.State BulkInsert(System.Collections.Generic.List<string> AcodeArray, System.Collections.Generic.List<string> UserArray, int DID, int CreatPepleID) {
            return base.Channel.BulkInsert(AcodeArray, UserArray, DID, CreatPepleID);
        }
        
        public string GetScoreHtml(WebPages.DistributeRecordService.SpecialReportReport lr) {
            return base.Channel.GetScoreHtml(lr);
        }
        
        public string GetScoreHtmlS(WebPages.DistributeRecordService.SpecialReportReport lr) {
            return base.Channel.GetScoreHtmlS(lr);
        }
    }
}
