//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.AppointmentConsultService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributeWorkModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class DistributeWorkModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DWConsultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DWConsultTeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DWCreatePersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DWCreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DWDistributeWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DWEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DWEndHourAndMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DWMoveUpAppTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DWServiceUserAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DWStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DWStartHourAndMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QTIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSID {
            get {
                return this.CSIDField;
            }
            set {
                if ((this.CSIDField.Equals(value) != true)) {
                    this.CSIDField = value;
                    this.RaisePropertyChanged("CSID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CWID {
            get {
                return this.CWIDField;
            }
            set {
                if ((this.CWIDField.Equals(value) != true)) {
                    this.CWIDField = value;
                    this.RaisePropertyChanged("CWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DWConsultPlace {
            get {
                return this.DWConsultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.DWConsultPlaceField, value) != true)) {
                    this.DWConsultPlaceField = value;
                    this.RaisePropertyChanged("DWConsultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DWConsultTeacher {
            get {
                return this.DWConsultTeacherField;
            }
            set {
                if ((this.DWConsultTeacherField.Equals(value) != true)) {
                    this.DWConsultTeacherField = value;
                    this.RaisePropertyChanged("DWConsultTeacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DWCreatePerson {
            get {
                return this.DWCreatePersonField;
            }
            set {
                if ((this.DWCreatePersonField.Equals(value) != true)) {
                    this.DWCreatePersonField = value;
                    this.RaisePropertyChanged("DWCreatePerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DWCreateTime {
            get {
                return this.DWCreateTimeField;
            }
            set {
                if ((this.DWCreateTimeField.Equals(value) != true)) {
                    this.DWCreateTimeField = value;
                    this.RaisePropertyChanged("DWCreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DWDistributeWeek {
            get {
                return this.DWDistributeWeekField;
            }
            set {
                if ((object.ReferenceEquals(this.DWDistributeWeekField, value) != true)) {
                    this.DWDistributeWeekField = value;
                    this.RaisePropertyChanged("DWDistributeWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DWEndDate {
            get {
                return this.DWEndDateField;
            }
            set {
                if ((this.DWEndDateField.Equals(value) != true)) {
                    this.DWEndDateField = value;
                    this.RaisePropertyChanged("DWEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DWEndHourAndMinutes {
            get {
                return this.DWEndHourAndMinutesField;
            }
            set {
                if ((object.ReferenceEquals(this.DWEndHourAndMinutesField, value) != true)) {
                    this.DWEndHourAndMinutesField = value;
                    this.RaisePropertyChanged("DWEndHourAndMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DWID {
            get {
                return this.DWIDField;
            }
            set {
                if ((this.DWIDField.Equals(value) != true)) {
                    this.DWIDField = value;
                    this.RaisePropertyChanged("DWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DWMoveUpAppTime {
            get {
                return this.DWMoveUpAppTimeField;
            }
            set {
                if ((this.DWMoveUpAppTimeField.Equals(value) != true)) {
                    this.DWMoveUpAppTimeField = value;
                    this.RaisePropertyChanged("DWMoveUpAppTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DWServiceUserAmount {
            get {
                return this.DWServiceUserAmountField;
            }
            set {
                if ((this.DWServiceUserAmountField.Equals(value) != true)) {
                    this.DWServiceUserAmountField = value;
                    this.RaisePropertyChanged("DWServiceUserAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DWStartDate {
            get {
                return this.DWStartDateField;
            }
            set {
                if ((this.DWStartDateField.Equals(value) != true)) {
                    this.DWStartDateField = value;
                    this.RaisePropertyChanged("DWStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DWStartHourAndMinutes {
            get {
                return this.DWStartHourAndMinutesField;
            }
            set {
                if ((object.ReferenceEquals(this.DWStartHourAndMinutesField, value) != true)) {
                    this.DWStartHourAndMinutesField = value;
                    this.RaisePropertyChanged("DWStartHourAndMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QTID {
            get {
                return this.QTIDField;
            }
            set {
                if ((this.QTIDField.Equals(value) != true)) {
                    this.QTIDField = value;
                    this.RaisePropertyChanged("QTID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounselorModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class CounselorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntroduceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkilledFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Introduce {
            get {
                return this.IntroduceField;
            }
            set {
                if ((object.ReferenceEquals(this.IntroduceField, value) != true)) {
                    this.IntroduceField = value;
                    this.RaisePropertyChanged("Introduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkilledField {
            get {
                return this.SkilledFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SkilledFieldField, value) != true)) {
                    this.SkilledFieldField = value;
                    this.RaisePropertyChanged("SkilledField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributeWorkViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class DistributeWorkViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplyPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplyUserCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplyUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppointmentStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AwaitAuditPeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultResultCommentLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultSubjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultSubjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultWayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounselorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistributeWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistributeWorkIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndHourAndMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrevConsultDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefuseReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceUsersAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartHourAndMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThroughAuditPeopleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplyPerson {
            get {
                return this.ApplyPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplyPersonField, value) != true)) {
                    this.ApplyPersonField = value;
                    this.RaisePropertyChanged("ApplyPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplyUserCount {
            get {
                return this.ApplyUserCountField;
            }
            set {
                if ((this.ApplyUserCountField.Equals(value) != true)) {
                    this.ApplyUserCountField = value;
                    this.RaisePropertyChanged("ApplyUserCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplyUserID {
            get {
                return this.ApplyUserIDField;
            }
            set {
                if ((this.ApplyUserIDField.Equals(value) != true)) {
                    this.ApplyUserIDField = value;
                    this.RaisePropertyChanged("ApplyUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentID {
            get {
                return this.AppointmentIDField;
            }
            set {
                if ((this.AppointmentIDField.Equals(value) != true)) {
                    this.AppointmentIDField = value;
                    this.RaisePropertyChanged("AppointmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppointmentState {
            get {
                return this.AppointmentStateField;
            }
            set {
                if ((object.ReferenceEquals(this.AppointmentStateField, value) != true)) {
                    this.AppointmentStateField = value;
                    this.RaisePropertyChanged("AppointmentState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AwaitAuditPeople {
            get {
                return this.AwaitAuditPeopleField;
            }
            set {
                if ((this.AwaitAuditPeopleField.Equals(value) != true)) {
                    this.AwaitAuditPeopleField = value;
                    this.RaisePropertyChanged("AwaitAuditPeople");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultPlace {
            get {
                return this.ConsultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultPlaceField, value) != true)) {
                    this.ConsultPlaceField = value;
                    this.RaisePropertyChanged("ConsultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultResultCommentLevel {
            get {
                return this.ConsultResultCommentLevelField;
            }
            set {
                if ((this.ConsultResultCommentLevelField.Equals(value) != true)) {
                    this.ConsultResultCommentLevelField = value;
                    this.RaisePropertyChanged("ConsultResultCommentLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultSubject {
            get {
                return this.ConsultSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultSubjectField, value) != true)) {
                    this.ConsultSubjectField = value;
                    this.RaisePropertyChanged("ConsultSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultSubjectID {
            get {
                return this.ConsultSubjectIDField;
            }
            set {
                if ((this.ConsultSubjectIDField.Equals(value) != true)) {
                    this.ConsultSubjectIDField = value;
                    this.RaisePropertyChanged("ConsultSubjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultSubjectName {
            get {
                return this.ConsultSubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultSubjectNameField, value) != true)) {
                    this.ConsultSubjectNameField = value;
                    this.RaisePropertyChanged("ConsultSubjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultWay {
            get {
                return this.ConsultWayField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultWayField, value) != true)) {
                    this.ConsultWayField = value;
                    this.RaisePropertyChanged("ConsultWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultWayID {
            get {
                return this.ConsultWayIDField;
            }
            set {
                if ((this.ConsultWayIDField.Equals(value) != true)) {
                    this.ConsultWayIDField = value;
                    this.RaisePropertyChanged("ConsultWayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Counselor {
            get {
                return this.CounselorField;
            }
            set {
                if ((this.CounselorField.Equals(value) != true)) {
                    this.CounselorField = value;
                    this.RaisePropertyChanged("Counselor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistributeWeek {
            get {
                return this.DistributeWeekField;
            }
            set {
                if ((object.ReferenceEquals(this.DistributeWeekField, value) != true)) {
                    this.DistributeWeekField = value;
                    this.RaisePropertyChanged("DistributeWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistributeWorkID {
            get {
                return this.DistributeWorkIDField;
            }
            set {
                if ((this.DistributeWorkIDField.Equals(value) != true)) {
                    this.DistributeWorkIDField = value;
                    this.RaisePropertyChanged("DistributeWorkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndHourAndMinutes {
            get {
                return this.EndHourAndMinutesField;
            }
            set {
                if ((object.ReferenceEquals(this.EndHourAndMinutesField, value) != true)) {
                    this.EndHourAndMinutesField = value;
                    this.RaisePropertyChanged("EndHourAndMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrevConsultDateTime {
            get {
                return this.PrevConsultDateTimeField;
            }
            set {
                if ((this.PrevConsultDateTimeField.Equals(value) != true)) {
                    this.PrevConsultDateTimeField = value;
                    this.RaisePropertyChanged("PrevConsultDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionTypeID {
            get {
                return this.QuestionTypeIDField;
            }
            set {
                if ((this.QuestionTypeIDField.Equals(value) != true)) {
                    this.QuestionTypeIDField = value;
                    this.RaisePropertyChanged("QuestionTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionTypeName {
            get {
                return this.QuestionTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTypeNameField, value) != true)) {
                    this.QuestionTypeNameField = value;
                    this.RaisePropertyChanged("QuestionTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefuseReason {
            get {
                return this.RefuseReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.RefuseReasonField, value) != true)) {
                    this.RefuseReasonField = value;
                    this.RaisePropertyChanged("RefuseReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceUsersAmount {
            get {
                return this.ServiceUsersAmountField;
            }
            set {
                if ((this.ServiceUsersAmountField.Equals(value) != true)) {
                    this.ServiceUsersAmountField = value;
                    this.RaisePropertyChanged("ServiceUsersAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartHourAndMinutes {
            get {
                return this.StartHourAndMinutesField;
            }
            set {
                if ((object.ReferenceEquals(this.StartHourAndMinutesField, value) != true)) {
                    this.StartHourAndMinutesField = value;
                    this.RaisePropertyChanged("StartHourAndMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ThroughAuditPeople {
            get {
                return this.ThroughAuditPeopleField;
            }
            set {
                if ((this.ThroughAuditPeopleField.Equals(value) != true)) {
                    this.ThroughAuditPeopleField = value;
                    this.RaisePropertyChanged("ThroughAuditPeople");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultWayViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class ConsultWayViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultWayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultWayNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultWayID {
            get {
                return this.ConsultWayIDField;
            }
            set {
                if ((this.ConsultWayIDField.Equals(value) != true)) {
                    this.ConsultWayIDField = value;
                    this.RaisePropertyChanged("ConsultWayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultWayName {
            get {
                return this.ConsultWayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultWayNameField, value) != true)) {
                    this.ConsultWayNameField = value;
                    this.RaisePropertyChanged("ConsultWayName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultSubjectViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class ConsultSubjectViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultSubjectApplyConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultSubjectContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultSubjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultSubjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultSubjectTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultSubjectApplyCondition {
            get {
                return this.ConsultSubjectApplyConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultSubjectApplyConditionField, value) != true)) {
                    this.ConsultSubjectApplyConditionField = value;
                    this.RaisePropertyChanged("ConsultSubjectApplyCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultSubjectContent {
            get {
                return this.ConsultSubjectContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultSubjectContentField, value) != true)) {
                    this.ConsultSubjectContentField = value;
                    this.RaisePropertyChanged("ConsultSubjectContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultSubjectID {
            get {
                return this.ConsultSubjectIDField;
            }
            set {
                if ((this.ConsultSubjectIDField.Equals(value) != true)) {
                    this.ConsultSubjectIDField = value;
                    this.RaisePropertyChanged("ConsultSubjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultSubjectName {
            get {
                return this.ConsultSubjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultSubjectNameField, value) != true)) {
                    this.ConsultSubjectNameField = value;
                    this.RaisePropertyChanged("ConsultSubjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultSubjectTypeName {
            get {
                return this.ConsultSubjectTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultSubjectTypeNameField, value) != true)) {
                    this.ConsultSubjectTypeNameField = value;
                    this.RaisePropertyChanged("ConsultSubjectTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultSubjectModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class ConsultSubjectModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSApplyConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCreatePersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSCreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QTIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSApplyCondition {
            get {
                return this.CSApplyConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.CSApplyConditionField, value) != true)) {
                    this.CSApplyConditionField = value;
                    this.RaisePropertyChanged("CSApplyCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSContent {
            get {
                return this.CSContentField;
            }
            set {
                if ((object.ReferenceEquals(this.CSContentField, value) != true)) {
                    this.CSContentField = value;
                    this.RaisePropertyChanged("CSContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCreatePerson {
            get {
                return this.CSCreatePersonField;
            }
            set {
                if ((this.CSCreatePersonField.Equals(value) != true)) {
                    this.CSCreatePersonField = value;
                    this.RaisePropertyChanged("CSCreatePerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSCreateTime {
            get {
                return this.CSCreateTimeField;
            }
            set {
                if ((this.CSCreateTimeField.Equals(value) != true)) {
                    this.CSCreateTimeField = value;
                    this.RaisePropertyChanged("CSCreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSID {
            get {
                return this.CSIDField;
            }
            set {
                if ((this.CSIDField.Equals(value) != true)) {
                    this.CSIDField = value;
                    this.RaisePropertyChanged("CSID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSName {
            get {
                return this.CSNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CSNameField, value) != true)) {
                    this.CSNameField = value;
                    this.RaisePropertyChanged("CSName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseCode {
            get {
                return this.EnterpriseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseCodeField, value) != true)) {
                    this.EnterpriseCodeField = value;
                    this.RaisePropertyChanged("EnterpriseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QTID {
            get {
                return this.QTIDField;
            }
            set {
                if ((this.QTIDField.Equals(value) != true)) {
                    this.QTIDField = value;
                    this.RaisePropertyChanged("QTID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionTypeViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.QuestionTypeModel")]
    [System.SerializableAttribute()]
    public partial class QuestionTypeViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionTypeID {
            get {
                return this.QuestionTypeIDField;
            }
            set {
                if ((this.QuestionTypeIDField.Equals(value) != true)) {
                    this.QuestionTypeIDField = value;
                    this.RaisePropertyChanged("QuestionTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionTypeName {
            get {
                return this.QuestionTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTypeNameField, value) != true)) {
                    this.QuestionTypeNameField = value;
                    this.RaisePropertyChanged("QuestionTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentViewModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class AppointmentViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultWayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultWayName {
            get {
                return this.ConsultWayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultWayNameField, value) != true)) {
                    this.ConsultWayNameField = value;
                    this.RaisePropertyChanged("ConsultWayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactWay {
            get {
                return this.ContactWayField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactWayField, value) != true)) {
                    this.ContactWayField = value;
                    this.RaisePropertyChanged("ContactWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionDetail {
            get {
                return this.QuestionDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionDetailField, value) != true)) {
                    this.QuestionDetailField = value;
                    this.RaisePropertyChanged("QuestionDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionTypeName {
            get {
                return this.QuestionTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTypeNameField, value) != true)) {
                    this.QuestionTypeNameField = value;
                    this.RaisePropertyChanged("QuestionTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentBasicInfo", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class AppointmentBasicInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsultWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeopleCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultDate {
            get {
                return this.ConsultDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultDateField, value) != true)) {
                    this.ConsultDateField = value;
                    this.RaisePropertyChanged("ConsultDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultPlace {
            get {
                return this.ConsultPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultPlaceField, value) != true)) {
                    this.ConsultPlaceField = value;
                    this.RaisePropertyChanged("ConsultPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsultWay {
            get {
                return this.ConsultWayField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsultWayField, value) != true)) {
                    this.ConsultWayField = value;
                    this.RaisePropertyChanged("ConsultWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeopleCount {
            get {
                return this.PeopleCountField;
            }
            set {
                if ((this.PeopleCountField.Equals(value) != true)) {
                    this.PeopleCountField = value;
                    this.RaisePropertyChanged("PeopleCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class AppointmentModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ASIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionDescribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefuseReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ASID {
            get {
                return this.ASIDField;
            }
            set {
                if ((this.ASIDField.Equals(value) != true)) {
                    this.ASIDField = value;
                    this.RaisePropertyChanged("ASID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DWID {
            get {
                return this.DWIDField;
            }
            set {
                if ((this.DWIDField.Equals(value) != true)) {
                    this.DWIDField = value;
                    this.RaisePropertyChanged("DWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionDescribe {
            get {
                return this.QuestionDescribeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionDescribeField, value) != true)) {
                    this.QuestionDescribeField = value;
                    this.RaisePropertyChanged("QuestionDescribe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefuseReason {
            get {
                return this.RefuseReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.RefuseReasonField, value) != true)) {
                    this.RefuseReasonField = value;
                    this.RaisePropertyChanged("RefuseReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AwaitStateAppointmentModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.AppointmentConsultMode" +
        "l")]
    [System.SerializableAttribute()]
    public partial class AwaitStateAppointmentModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((this.AppIDField.Equals(value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppointmentConsultService.IAppointmentConsultService")]
    public interface IAppointmentConsultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/AddDistributeWork", ReplyAction="http://tempuri.org/IAppointmentConsultService/AddDistributeWorkResponse")]
        int AddDistributeWork(WebPages.AppointmentConsultService.DistributeWorkModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetAllCounselorByEnterpriseCode", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetAllCounselorByEnterpriseCodeResp" +
            "onse")]
        System.Collections.Generic.List<WebPages.AppointmentConsultService.CounselorModel> GetAllCounselorByEnterpriseCode(string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetDistributeWorkByUid", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetDistributeWorkByUidResponse")]
        System.Collections.Generic.List<WebPages.AppointmentConsultService.DistributeWorkViewModel> GetDistributeWorkByUid(int userRoleType, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetConsultWay", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetConsultWayResponse")]
        System.Collections.Generic.List<WebPages.AppointmentConsultService.ConsultWayViewModel> GetConsultWay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetConsultSubjectByEnterpriseCode", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetConsultSubjectByEnterpriseCodeRe" +
            "sponse")]
        System.Collections.Generic.List<WebPages.AppointmentConsultService.ConsultSubjectViewModel> GetConsultSubjectByEnterpriseCode(string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetConsultSubjectByID", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetConsultSubjectByIDResponse")]
        System.Collections.Generic.List<WebPages.AppointmentConsultService.ConsultSubjectViewModel> GetConsultSubjectByID(int consultSubjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/AddConsultSubject", ReplyAction="http://tempuri.org/IAppointmentConsultService/AddConsultSubjectResponse")]
        int AddConsultSubject(WebPages.AppointmentConsultService.ConsultSubjectModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetQuestionType", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetQuestionTypeResponse")]
        System.Collections.Generic.List<WebPages.AppointmentConsultService.QuestionTypeViewModel> GetQuestionType(string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/UpdateAppointmentInfo", ReplyAction="http://tempuri.org/IAppointmentConsultService/UpdateAppointmentInfoResponse")]
        bool UpdateAppointmentInfo(System.Data.DataTable dt, int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/DeleteDistributeWorkByID", ReplyAction="http://tempuri.org/IAppointmentConsultService/DeleteDistributeWorkByIDResponse")]
        int DeleteDistributeWorkByID(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetAppointmentResponse")]
        System.Data.DataSet GetAppointment(int startPageIndex, int endPageIndex, int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetAppointmentInfo", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetAppointmentInfoResponse")]
        WebPages.AppointmentConsultService.AppointmentViewModel GetAppointmentInfo(int appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/AcceptApply", ReplyAction="http://tempuri.org/IAppointmentConsultService/AcceptApplyResponse")]
        int AcceptApply(int distributeWorkID, int appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/RefuseApply", ReplyAction="http://tempuri.org/IAppointmentConsultService/RefuseApplyResponse")]
        int RefuseApply(int appID, string refuseReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetAppointmentHeaderInfo", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetAppointmentHeaderInfoResponse")]
        WebPages.AppointmentConsultService.AppointmentBasicInfo GetAppointmentHeaderInfo(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetAppointmentPeopleCount", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetAppointmentPeopleCountResponse")]
        int GetAppointmentPeopleCount(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetDistriID", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetDistriIDResponse")]
        int GetDistriID(string date, string time, int counselorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/UserApplyAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/UserApplyAppointmentResponse")]
        bool UserApplyAppointment(WebPages.AppointmentConsultService.AppointmentModel model, string tel, int questionTypeID, int userRoleTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/DeleteAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/DeleteAppointmentResponse")]
        int DeleteAppointment(int distriID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/AddConsultResultComment", ReplyAction="http://tempuri.org/IAppointmentConsultService/AddConsultResultCommentResponse")]
        int AddConsultResultComment(int appID, int level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/RefuseAndReturnDistriID", ReplyAction="http://tempuri.org/IAppointmentConsultService/RefuseAndReturnDistriIDResponse")]
        System.Collections.Generic.List<int> RefuseAndReturnDistriID(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/IsAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/IsAppointmentResponse")]
        int IsAppointment(int distriID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetApplyPerson", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetApplyPersonResponse")]
        string GetApplyPerson(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetAwaitStateAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetAwaitStateAppointmentResponse")]
        System.Collections.Generic.List<WebPages.AppointmentConsultService.AwaitStateAppointmentModel> GetAwaitStateAppointment(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetThroughtCreditPeopleCount", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetThroughtCreditPeopleCountRespons" +
            "e")]
        int GetThroughtCreditPeopleCount(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/JudgeSubjectRepeat", ReplyAction="http://tempuri.org/IAppointmentConsultService/JudgeSubjectRepeatResponse")]
        int JudgeSubjectRepeat(string subjectName, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/CancelAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/CancelAppointmentResponse")]
        bool CancelAppointment(int distributeWorkID, int appointmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/JudgeAppointmentIsComment", ReplyAction="http://tempuri.org/IAppointmentConsultService/JudgeAppointmentIsCommentResponse")]
        int JudgeAppointmentIsComment(int distributeWorkID, int appointmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetAppointmentIsComment", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetAppointmentIsCommentResponse")]
        int GetAppointmentIsComment(int userID, int questionTypeID, int counselorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/DeleteSubject", ReplyAction="http://tempuri.org/IAppointmentConsultService/DeleteSubjectResponse")]
        int DeleteSubject(int subjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetExpectationServicePeopleCount", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetExpectationServicePeopleCountRes" +
            "ponse")]
        int GetExpectationServicePeopleCount(int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/GetViewAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/GetViewAppointmentResponse")]
        System.Data.DataSet GetViewAppointment(int startPageIndex, int endPageIndex, int distriID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentConsultService/JudgeIsAppointment", ReplyAction="http://tempuri.org/IAppointmentConsultService/JudgeIsAppointmentResponse")]
        int JudgeIsAppointment(int distributeWorkID, int userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppointmentConsultServiceChannel : WebPages.AppointmentConsultService.IAppointmentConsultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppointmentConsultServiceClient : System.ServiceModel.ClientBase<WebPages.AppointmentConsultService.IAppointmentConsultService>, WebPages.AppointmentConsultService.IAppointmentConsultService {
        
        public AppointmentConsultServiceClient() {
        }
        
        public AppointmentConsultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppointmentConsultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentConsultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentConsultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddDistributeWork(WebPages.AppointmentConsultService.DistributeWorkModel model) {
            return base.Channel.AddDistributeWork(model);
        }
        
        public System.Collections.Generic.List<WebPages.AppointmentConsultService.CounselorModel> GetAllCounselorByEnterpriseCode(string enterpriseCode) {
            return base.Channel.GetAllCounselorByEnterpriseCode(enterpriseCode);
        }
        
        public System.Collections.Generic.List<WebPages.AppointmentConsultService.DistributeWorkViewModel> GetDistributeWorkByUid(int userRoleType, int uid) {
            return base.Channel.GetDistributeWorkByUid(userRoleType, uid);
        }
        
        public System.Collections.Generic.List<WebPages.AppointmentConsultService.ConsultWayViewModel> GetConsultWay() {
            return base.Channel.GetConsultWay();
        }
        
        public System.Collections.Generic.List<WebPages.AppointmentConsultService.ConsultSubjectViewModel> GetConsultSubjectByEnterpriseCode(string enterpriseCode) {
            return base.Channel.GetConsultSubjectByEnterpriseCode(enterpriseCode);
        }
        
        public System.Collections.Generic.List<WebPages.AppointmentConsultService.ConsultSubjectViewModel> GetConsultSubjectByID(int consultSubjectID) {
            return base.Channel.GetConsultSubjectByID(consultSubjectID);
        }
        
        public int AddConsultSubject(WebPages.AppointmentConsultService.ConsultSubjectModel model) {
            return base.Channel.AddConsultSubject(model);
        }
        
        public System.Collections.Generic.List<WebPages.AppointmentConsultService.QuestionTypeViewModel> GetQuestionType(string enterpriseCode) {
            return base.Channel.GetQuestionType(enterpriseCode);
        }
        
        public bool UpdateAppointmentInfo(System.Data.DataTable dt, int distriID) {
            return base.Channel.UpdateAppointmentInfo(dt, distriID);
        }
        
        public int DeleteDistributeWorkByID(int distriID) {
            return base.Channel.DeleteDistributeWorkByID(distriID);
        }
        
        public System.Data.DataSet GetAppointment(int startPageIndex, int endPageIndex, int distriID) {
            return base.Channel.GetAppointment(startPageIndex, endPageIndex, distriID);
        }
        
        public WebPages.AppointmentConsultService.AppointmentViewModel GetAppointmentInfo(int appID) {
            return base.Channel.GetAppointmentInfo(appID);
        }
        
        public int AcceptApply(int distributeWorkID, int appID) {
            return base.Channel.AcceptApply(distributeWorkID, appID);
        }
        
        public int RefuseApply(int appID, string refuseReason) {
            return base.Channel.RefuseApply(appID, refuseReason);
        }
        
        public WebPages.AppointmentConsultService.AppointmentBasicInfo GetAppointmentHeaderInfo(int distriID) {
            return base.Channel.GetAppointmentHeaderInfo(distriID);
        }
        
        public int GetAppointmentPeopleCount(int distriID) {
            return base.Channel.GetAppointmentPeopleCount(distriID);
        }
        
        public int GetDistriID(string date, string time, int counselorID) {
            return base.Channel.GetDistriID(date, time, counselorID);
        }
        
        public bool UserApplyAppointment(WebPages.AppointmentConsultService.AppointmentModel model, string tel, int questionTypeID, int userRoleTypeID) {
            return base.Channel.UserApplyAppointment(model, tel, questionTypeID, userRoleTypeID);
        }
        
        public int DeleteAppointment(int distriID, int userID) {
            return base.Channel.DeleteAppointment(distriID, userID);
        }
        
        public int AddConsultResultComment(int appID, int level) {
            return base.Channel.AddConsultResultComment(appID, level);
        }
        
        public System.Collections.Generic.List<int> RefuseAndReturnDistriID(int distriID) {
            return base.Channel.RefuseAndReturnDistriID(distriID);
        }
        
        public int IsAppointment(int distriID, int userID) {
            return base.Channel.IsAppointment(distriID, userID);
        }
        
        public string GetApplyPerson(int distriID) {
            return base.Channel.GetApplyPerson(distriID);
        }
        
        public System.Collections.Generic.List<WebPages.AppointmentConsultService.AwaitStateAppointmentModel> GetAwaitStateAppointment(int distriID) {
            return base.Channel.GetAwaitStateAppointment(distriID);
        }
        
        public int GetThroughtCreditPeopleCount(int distriID) {
            return base.Channel.GetThroughtCreditPeopleCount(distriID);
        }
        
        public int JudgeSubjectRepeat(string subjectName, string enterpriseCode) {
            return base.Channel.JudgeSubjectRepeat(subjectName, enterpriseCode);
        }
        
        public bool CancelAppointment(int distributeWorkID, int appointmentID) {
            return base.Channel.CancelAppointment(distributeWorkID, appointmentID);
        }
        
        public int JudgeAppointmentIsComment(int distributeWorkID, int appointmentID) {
            return base.Channel.JudgeAppointmentIsComment(distributeWorkID, appointmentID);
        }
        
        public int GetAppointmentIsComment(int userID, int questionTypeID, int counselorID) {
            return base.Channel.GetAppointmentIsComment(userID, questionTypeID, counselorID);
        }
        
        public int DeleteSubject(int subjectID) {
            return base.Channel.DeleteSubject(subjectID);
        }
        
        public int GetExpectationServicePeopleCount(int distriID) {
            return base.Channel.GetExpectationServicePeopleCount(distriID);
        }
        
        public System.Data.DataSet GetViewAppointment(int startPageIndex, int endPageIndex, int distriID) {
            return base.Channel.GetViewAppointment(startPageIndex, endPageIndex, distriID);
        }
        
        public int JudgeIsAppointment(int distributeWorkID, int userID) {
            return base.Channel.JudgeIsAppointment(distributeWorkID, userID);
        }
    }
}
