//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.PersonalReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalReportAddEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.PersonalReportModel")]
    [System.SerializableAttribute()]
    public partial class PersonalReportAddEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _ReporTypeField;
        
        private string _acode_idField;
        
        private int _answeraddidField;
        
        private string _pradd_dimensionField;
        
        private int _pradd_idField;
        
        private string _pradd_newaddField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ReporType {
            get {
                return this._ReporTypeField;
            }
            set {
                if ((this._ReporTypeField.Equals(value) != true)) {
                    this._ReporTypeField = value;
                    this.RaisePropertyChanged("_ReporType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _acode_id {
            get {
                return this._acode_idField;
            }
            set {
                if ((object.ReferenceEquals(this._acode_idField, value) != true)) {
                    this._acode_idField = value;
                    this.RaisePropertyChanged("_acode_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answeraddid {
            get {
                return this._answeraddidField;
            }
            set {
                if ((this._answeraddidField.Equals(value) != true)) {
                    this._answeraddidField = value;
                    this.RaisePropertyChanged("_answeraddid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _pradd_dimension {
            get {
                return this._pradd_dimensionField;
            }
            set {
                if ((object.ReferenceEquals(this._pradd_dimensionField, value) != true)) {
                    this._pradd_dimensionField = value;
                    this.RaisePropertyChanged("_pradd_dimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _pradd_id {
            get {
                return this._pradd_idField;
            }
            set {
                if ((this._pradd_idField.Equals(value) != true)) {
                    this._pradd_idField = value;
                    this.RaisePropertyChanged("_pradd_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _pradd_newadd {
            get {
                return this._pradd_newaddField;
            }
            set {
                if ((object.ReferenceEquals(this._pradd_newaddField, value) != true)) {
                    this._pradd_newaddField = value;
                    this.RaisePropertyChanged("_pradd_newadd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PushStatusEntitys", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.PushStatusModel")]
    [System.SerializableAttribute()]
    public partial class PushStatusEntitys : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _answeraddidField;
        
        private int _psidField;
        
        private int _psstateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answeraddid {
            get {
                return this._answeraddidField;
            }
            set {
                if ((this._answeraddidField.Equals(value) != true)) {
                    this._answeraddidField = value;
                    this.RaisePropertyChanged("_answeraddid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _psid {
            get {
                return this._psidField;
            }
            set {
                if ((this._psidField.Equals(value) != true)) {
                    this._psidField = value;
                    this.RaisePropertyChanged("_psid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _psstate {
            get {
                return this._psstateField;
            }
            set {
                if ((this._psstateField.Equals(value) != true)) {
                    this._psstateField = value;
                    this.RaisePropertyChanged("_psstate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="R_ReportEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.R_ReportEntity")]
    [System.SerializableAttribute()]
    public partial class R_ReportEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int _answeidField;
        
        private int _createuidField;
        
        private string _r_codeField;
        
        private System.DateTime _r_createdateField;
        
        private int _r_idField;
        
        private string _reportjsonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _answeid {
            get {
                return this._answeidField;
            }
            set {
                if ((this._answeidField.Equals(value) != true)) {
                    this._answeidField = value;
                    this.RaisePropertyChanged("_answeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _createuid {
            get {
                return this._createuidField;
            }
            set {
                if ((this._createuidField.Equals(value) != true)) {
                    this._createuidField = value;
                    this.RaisePropertyChanged("_createuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _r_code {
            get {
                return this._r_codeField;
            }
            set {
                if ((object.ReferenceEquals(this._r_codeField, value) != true)) {
                    this._r_codeField = value;
                    this.RaisePropertyChanged("_r_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _r_createdate {
            get {
                return this._r_createdateField;
            }
            set {
                if ((this._r_createdateField.Equals(value) != true)) {
                    this._r_createdateField = value;
                    this.RaisePropertyChanged("_r_createdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _r_id {
            get {
                return this._r_idField;
            }
            set {
                if ((this._r_idField.Equals(value) != true)) {
                    this._r_idField = value;
                    this.RaisePropertyChanged("_r_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _reportjson {
            get {
                return this._reportjsonField;
            }
            set {
                if ((object.ReferenceEquals(this._reportjsonField, value) != true)) {
                    this._reportjsonField = value;
                    this.RaisePropertyChanged("_reportjson");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonalReportService.IPersonalReportService")]
    public interface IPersonalReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/InitiPersonalReportTable", ReplyAction="http://tempuri.org/IPersonalReportService/InitiPersonalReportTableResponse")]
        System.Data.DataSet InitiPersonalReportTable(int Uid, int Amount_TypeID, int Amount_ID, int D_ID, string DistributionName, int PSstate, string Name, string EnterpriseCode, int StarPageIndex, int EndPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/PRInsert", ReplyAction="http://tempuri.org/IPersonalReportService/PRInsertResponse")]
        long PRInsert(WebPages.PersonalReportService.PersonalReportAddEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/Update", ReplyAction="http://tempuri.org/IPersonalReportService/UpdateResponse")]
        bool Update(WebPages.PersonalReportService.PersonalReportAddEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/UpdateByAnswerID", ReplyAction="http://tempuri.org/IPersonalReportService/UpdateByAnswerIDResponse")]
        bool UpdateByAnswerID(WebPages.PersonalReportService.PersonalReportAddEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/GetPersonExcel", ReplyAction="http://tempuri.org/IPersonalReportService/GetPersonExcelResponse")]
        void GetPersonExcel(string AUserID, string CreatePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/Insert", ReplyAction="http://tempuri.org/IPersonalReportService/InsertResponse")]
        long Insert(WebPages.PersonalReportService.PushStatusEntitys entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/R_ReportInsert", ReplyAction="http://tempuri.org/IPersonalReportService/R_ReportInsertResponse")]
        long R_ReportInsert(WebPages.PersonalReportService.R_ReportEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/GetReportList", ReplyAction="http://tempuri.org/IPersonalReportService/GetReportListResponse")]
        System.Data.DataSet GetReportList(string AmountCode, int AnswerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonalReportService/ReportExport", ReplyAction="http://tempuri.org/IPersonalReportService/ReportExportResponse")]
        System.Data.DataSet ReportExport(string AnswerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonalReportServiceChannel : WebPages.PersonalReportService.IPersonalReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonalReportServiceClient : System.ServiceModel.ClientBase<WebPages.PersonalReportService.IPersonalReportService>, WebPages.PersonalReportService.IPersonalReportService {
        
        public PersonalReportServiceClient() {
        }
        
        public PersonalReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonalReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet InitiPersonalReportTable(int Uid, int Amount_TypeID, int Amount_ID, int D_ID, string DistributionName, int PSstate, string Name, string EnterpriseCode, int StarPageIndex, int EndPageIndex) {
            return base.Channel.InitiPersonalReportTable(Uid, Amount_TypeID, Amount_ID, D_ID, DistributionName, PSstate, Name, EnterpriseCode, StarPageIndex, EndPageIndex);
        }
        
        public long PRInsert(WebPages.PersonalReportService.PersonalReportAddEntity entityInfo) {
            return base.Channel.PRInsert(entityInfo);
        }
        
        public bool Update(WebPages.PersonalReportService.PersonalReportAddEntity entityInfo) {
            return base.Channel.Update(entityInfo);
        }
        
        public bool UpdateByAnswerID(WebPages.PersonalReportService.PersonalReportAddEntity entityInfo) {
            return base.Channel.UpdateByAnswerID(entityInfo);
        }
        
        public void GetPersonExcel(string AUserID, string CreatePath) {
            base.Channel.GetPersonExcel(AUserID, CreatePath);
        }
        
        public long Insert(WebPages.PersonalReportService.PushStatusEntitys entityInfo) {
            return base.Channel.Insert(entityInfo);
        }
        
        public long R_ReportInsert(WebPages.PersonalReportService.R_ReportEntity entityInfo) {
            return base.Channel.R_ReportInsert(entityInfo);
        }
        
        public System.Data.DataSet GetReportList(string AmountCode, int AnswerID) {
            return base.Channel.GetReportList(AmountCode, AnswerID);
        }
        
        public System.Data.DataSet ReportExport(string AnswerID) {
            return base.Channel.ReportExport(AnswerID);
        }
    }
}
