//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.QuestionnaireService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Questionnaire_InfoEntity", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.QuestionnaireModel")]
    [System.SerializableAttribute()]
    public partial class Questionnaire_InfoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _codeField;
        
        private System.DateTime _createDateField;
        
        private string _enterpriseCodeField;
        
        private long _idField;
        
        private string _instructionField;
        
        private bool _isDeleteField;
        
        private bool _isFinishField;
        
        private string _jianPinField;
        
        private string _nameField;
        
        private string _pinYinField;
        
        private bool _stateField;
        
        private long _uIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _code {
            get {
                return this._codeField;
            }
            set {
                if ((object.ReferenceEquals(this._codeField, value) != true)) {
                    this._codeField = value;
                    this.RaisePropertyChanged("_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate {
            get {
                return this._createDateField;
            }
            set {
                if ((this._createDateField.Equals(value) != true)) {
                    this._createDateField = value;
                    this.RaisePropertyChanged("_createDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _enterpriseCode {
            get {
                return this._enterpriseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this._enterpriseCodeField, value) != true)) {
                    this._enterpriseCodeField = value;
                    this.RaisePropertyChanged("_enterpriseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _instruction {
            get {
                return this._instructionField;
            }
            set {
                if ((object.ReferenceEquals(this._instructionField, value) != true)) {
                    this._instructionField = value;
                    this.RaisePropertyChanged("_instruction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _isDelete {
            get {
                return this._isDeleteField;
            }
            set {
                if ((this._isDeleteField.Equals(value) != true)) {
                    this._isDeleteField = value;
                    this.RaisePropertyChanged("_isDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _isFinish {
            get {
                return this._isFinishField;
            }
            set {
                if ((this._isFinishField.Equals(value) != true)) {
                    this._isFinishField = value;
                    this.RaisePropertyChanged("_isFinish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _jianPin {
            get {
                return this._jianPinField;
            }
            set {
                if ((object.ReferenceEquals(this._jianPinField, value) != true)) {
                    this._jianPinField = value;
                    this.RaisePropertyChanged("_jianPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _pinYin {
            get {
                return this._pinYinField;
            }
            set {
                if ((object.ReferenceEquals(this._pinYinField, value) != true)) {
                    this._pinYinField = value;
                    this.RaisePropertyChanged("_pinYin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _state {
            get {
                return this._stateField;
            }
            set {
                if ((this._stateField.Equals(value) != true)) {
                    this._stateField = value;
                    this.RaisePropertyChanged("_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _uId {
            get {
                return this._uIdField;
            }
            set {
                if ((this._uIdField.Equals(value) != true)) {
                    this._uIdField = value;
                    this.RaisePropertyChanged("_uId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Questionnaire_Respondence", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.QuestionnaireModel")]
    [System.SerializableAttribute()]
    public partial class Questionnaire_Respondence : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnsRecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnwserPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Is_AnonymityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Is_DeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QD_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Q_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SubmitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long U_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnsRecord {
            get {
                return this.AnsRecordField;
            }
            set {
                if ((object.ReferenceEquals(this.AnsRecordField, value) != true)) {
                    this.AnsRecordField = value;
                    this.RaisePropertyChanged("AnsRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnwserPath {
            get {
                return this.AnwserPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AnwserPathField, value) != true)) {
                    this.AnwserPathField = value;
                    this.RaisePropertyChanged("AnwserPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Is_Anonymity {
            get {
                return this.Is_AnonymityField;
            }
            set {
                if ((this.Is_AnonymityField.Equals(value) != true)) {
                    this.Is_AnonymityField = value;
                    this.RaisePropertyChanged("Is_Anonymity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Is_Delete {
            get {
                return this.Is_DeleteField;
            }
            set {
                if ((this.Is_DeleteField.Equals(value) != true)) {
                    this.Is_DeleteField = value;
                    this.RaisePropertyChanged("Is_Delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QD_Code {
            get {
                return this.QD_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.QD_CodeField, value) != true)) {
                    this.QD_CodeField = value;
                    this.RaisePropertyChanged("QD_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Q_Code {
            get {
                return this.Q_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Q_CodeField, value) != true)) {
                    this.Q_CodeField = value;
                    this.RaisePropertyChanged("Q_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubmitTime {
            get {
                return this.SubmitTimeField;
            }
            set {
                if ((this.SubmitTimeField.Equals(value) != true)) {
                    this.SubmitTimeField = value;
                    this.RaisePropertyChanged("SubmitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long U_ID {
            get {
                return this.U_IDField;
            }
            set {
                if ((this.U_IDField.Equals(value) != true)) {
                    this.U_IDField = value;
                    this.RaisePropertyChanged("U_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuestionnaireService.IQuestionnaireService")]
    public interface IQuestionnaireService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetQuestionnaireInfo", ReplyAction="http://tempuri.org/IQuestionnaireService/GetQuestionnaireInfoResponse")]
        System.Data.DataSet GetQuestionnaireInfo(long uId, string questionnaireName, System.Nullable<int> state, System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, string enterpriseCode, int startPageIndex, int endPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/SaveQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/SaveQuestionnaireResponse")]
        int SaveQuestionnaire(string jsonString, string name, long uId, string enterpriseCode, string guidanceStr, bool isFinish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/DeleteQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/DeleteQuestionnaireResponse")]
        int DeleteQuestionnaire(string quesCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/PreviewQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/PreviewQuestionnaireResponse")]
        System.Data.DataTable PreviewQuestionnaire(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/CheckNameRepeat", ReplyAction="http://tempuri.org/IQuestionnaireService/CheckNameRepeatResponse")]
        int CheckNameRepeat(string name, string enterprisecode, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/UpdateQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/UpdateQuestionnaireResponse")]
        int UpdateQuestionnaire(string code, string jsonList, string name, string instruct, bool isFinish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/InitiDistributeRecordTable", ReplyAction="http://tempuri.org/IQuestionnaireService/InitiDistributeRecordTableResponse")]
        System.Data.DataSet InitiDistributeRecordTable(int userID, string enterpriseCode, int state, string quesName, string loginName, int departId, System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, int ansState, int StarPageIndex, int EndPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/DeleteDistributeRecord", ReplyAction="http://tempuri.org/IQuestionnaireService/DeleteDistributeRecordResponse")]
        int DeleteDistributeRecord(string[] upId, string[] deleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/BeforeDelete", ReplyAction="http://tempuri.org/IQuestionnaireService/BeforeDeleteResponse")]
        System.Data.DataTable BeforeDelete(string ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetMyQuestionnaire", ReplyAction="http://tempuri.org/IQuestionnaireService/GetMyQuestionnaireResponse")]
        System.Data.DataSet GetMyQuestionnaire(int userId, int starPageIndex, int endPageIndex, string quesName, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetQuestionnaire_SubjectCount", ReplyAction="http://tempuri.org/IQuestionnaireService/GetQuestionnaire_SubjectCountResponse")]
        int GetQuestionnaire_SubjectCount(string q_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetLikeName", ReplyAction="http://tempuri.org/IQuestionnaireService/GetLikeNameResponse")]
        System.Data.DataTable GetLikeName(string queName, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetEntity", ReplyAction="http://tempuri.org/IQuestionnaireService/GetEntityResponse")]
        WebPages.QuestionnaireService.Questionnaire_InfoEntity GetEntity(string queCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetOperation_Subject_Temp", ReplyAction="http://tempuri.org/IQuestionnaireService/GetOperation_Subject_TempResponse")]
        System.Data.DataTable GetOperation_Subject_Temp(string subCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetOperationTemp", ReplyAction="http://tempuri.org/IQuestionnaireService/GetOperationTempResponse")]
        System.Data.DataTable GetOperationTemp(string opCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetSubjectEntity", ReplyAction="http://tempuri.org/IQuestionnaireService/GetSubjectEntityResponse")]
        System.Data.DataTable GetSubjectEntity(string opCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/UpdateAnswer", ReplyAction="http://tempuri.org/IQuestionnaireService/UpdateAnswerResponse")]
        bool UpdateAnswer(WebPages.QuestionnaireService.Questionnaire_Respondence entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetEntity_Respod", ReplyAction="http://tempuri.org/IQuestionnaireService/GetEntity_RespodResponse")]
        WebPages.QuestionnaireService.Questionnaire_Respondence GetEntity_Respod(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/SaveAnwserRecord", ReplyAction="http://tempuri.org/IQuestionnaireService/SaveAnwserRecordResponse")]
        int SaveAnwserRecord(WebPages.QuestionnaireService.Questionnaire_Respondence respond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetAnwserRecord", ReplyAction="http://tempuri.org/IQuestionnaireService/GetAnwserRecordResponse")]
        System.Data.DataSet GetAnwserRecord(int uId, string quesName, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, int startpage, int endpage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/DeleteAnwserRecord", ReplyAction="http://tempuri.org/IQuestionnaireService/DeleteAnwserRecordResponse")]
        bool DeleteAnwserRecord(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/CalculateScore", ReplyAction="http://tempuri.org/IQuestionnaireService/CalculateScoreResponse")]
        double CalculateScore(string tzId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/InitSurveyResult", ReplyAction="http://tempuri.org/IQuestionnaireService/InitSurveyResultResponse")]
        System.Data.DataSet InitSurveyResult(int uId, string enterpriseCode, string queName, int startPage, int endPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/AnwserGather", ReplyAction="http://tempuri.org/IQuestionnaireService/AnwserGatherResponse")]
        System.Data.DataSet AnwserGather(int uId, string qCode, string uName, string enterpriseCode, string dId, System.DateTime start, System.DateTime end, int startPage, int endPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetCount", ReplyAction="http://tempuri.org/IQuestionnaireService/GetCountResponse")]
        long GetCount(string qCode, int disUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/GetResponse", ReplyAction="http://tempuri.org/IQuestionnaireService/GetResponseResponse")]
        System.Data.DataTable GetResponse(string qCode, int uId, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionnaireService/CheckQuestionnaire_IsAnwser", ReplyAction="http://tempuri.org/IQuestionnaireService/CheckQuestionnaire_IsAnwserResponse")]
        int CheckQuestionnaire_IsAnwser(string qCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuestionnaireServiceChannel : WebPages.QuestionnaireService.IQuestionnaireService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuestionnaireServiceClient : System.ServiceModel.ClientBase<WebPages.QuestionnaireService.IQuestionnaireService>, WebPages.QuestionnaireService.IQuestionnaireService {
        
        public QuestionnaireServiceClient() {
        }
        
        public QuestionnaireServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuestionnaireServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionnaireServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionnaireServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetQuestionnaireInfo(long uId, string questionnaireName, System.Nullable<int> state, System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, string enterpriseCode, int startPageIndex, int endPageIndex) {
            return base.Channel.GetQuestionnaireInfo(uId, questionnaireName, state, startTime, endTime, enterpriseCode, startPageIndex, endPageIndex);
        }
        
        public int SaveQuestionnaire(string jsonString, string name, long uId, string enterpriseCode, string guidanceStr, bool isFinish) {
            return base.Channel.SaveQuestionnaire(jsonString, name, uId, enterpriseCode, guidanceStr, isFinish);
        }
        
        public int DeleteQuestionnaire(string quesCode) {
            return base.Channel.DeleteQuestionnaire(quesCode);
        }
        
        public System.Data.DataTable PreviewQuestionnaire(string code) {
            return base.Channel.PreviewQuestionnaire(code);
        }
        
        public int CheckNameRepeat(string name, string enterprisecode, string code) {
            return base.Channel.CheckNameRepeat(name, enterprisecode, code);
        }
        
        public int UpdateQuestionnaire(string code, string jsonList, string name, string instruct, bool isFinish) {
            return base.Channel.UpdateQuestionnaire(code, jsonList, name, instruct, isFinish);
        }
        
        public System.Data.DataSet InitiDistributeRecordTable(int userID, string enterpriseCode, int state, string quesName, string loginName, int departId, System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, int ansState, int StarPageIndex, int EndPageIndex) {
            return base.Channel.InitiDistributeRecordTable(userID, enterpriseCode, state, quesName, loginName, departId, startTime, endTime, ansState, StarPageIndex, EndPageIndex);
        }
        
        public int DeleteDistributeRecord(string[] upId, string[] deleId) {
            return base.Channel.DeleteDistributeRecord(upId, deleId);
        }
        
        public System.Data.DataTable BeforeDelete(string ids) {
            return base.Channel.BeforeDelete(ids);
        }
        
        public System.Data.DataSet GetMyQuestionnaire(int userId, int starPageIndex, int endPageIndex, string quesName, string enterpriseCode) {
            return base.Channel.GetMyQuestionnaire(userId, starPageIndex, endPageIndex, quesName, enterpriseCode);
        }
        
        public int GetQuestionnaire_SubjectCount(string q_Code) {
            return base.Channel.GetQuestionnaire_SubjectCount(q_Code);
        }
        
        public System.Data.DataTable GetLikeName(string queName, string enterpriseCode) {
            return base.Channel.GetLikeName(queName, enterpriseCode);
        }
        
        public WebPages.QuestionnaireService.Questionnaire_InfoEntity GetEntity(string queCode) {
            return base.Channel.GetEntity(queCode);
        }
        
        public System.Data.DataTable GetOperation_Subject_Temp(string subCode) {
            return base.Channel.GetOperation_Subject_Temp(subCode);
        }
        
        public System.Data.DataTable GetOperationTemp(string opCode) {
            return base.Channel.GetOperationTemp(opCode);
        }
        
        public System.Data.DataTable GetSubjectEntity(string opCode) {
            return base.Channel.GetSubjectEntity(opCode);
        }
        
        public bool UpdateAnswer(WebPages.QuestionnaireService.Questionnaire_Respondence entity) {
            return base.Channel.UpdateAnswer(entity);
        }
        
        public WebPages.QuestionnaireService.Questionnaire_Respondence GetEntity_Respod(string code) {
            return base.Channel.GetEntity_Respod(code);
        }
        
        public int SaveAnwserRecord(WebPages.QuestionnaireService.Questionnaire_Respondence respond) {
            return base.Channel.SaveAnwserRecord(respond);
        }
        
        public System.Data.DataSet GetAnwserRecord(int uId, string quesName, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, int startpage, int endpage) {
            return base.Channel.GetAnwserRecord(uId, quesName, start, end, startpage, endpage);
        }
        
        public bool DeleteAnwserRecord(string id) {
            return base.Channel.DeleteAnwserRecord(id);
        }
        
        public double CalculateScore(string tzId) {
            return base.Channel.CalculateScore(tzId);
        }
        
        public System.Data.DataSet InitSurveyResult(int uId, string enterpriseCode, string queName, int startPage, int endPage) {
            return base.Channel.InitSurveyResult(uId, enterpriseCode, queName, startPage, endPage);
        }
        
        public System.Data.DataSet AnwserGather(int uId, string qCode, string uName, string enterpriseCode, string dId, System.DateTime start, System.DateTime end, int startPage, int endPage) {
            return base.Channel.AnwserGather(uId, qCode, uName, enterpriseCode, dId, start, end, startPage, endPage);
        }
        
        public long GetCount(string qCode, int disUid) {
            return base.Channel.GetCount(qCode, disUid);
        }
        
        public System.Data.DataTable GetResponse(string qCode, int uId, string enterpriseCode) {
            return base.Channel.GetResponse(qCode, uId, enterpriseCode);
        }
        
        public int CheckQuestionnaire_IsAnwser(string qCode) {
            return base.Channel.CheckQuestionnaire_IsAnwser(qCode);
        }
    }
}
