//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.BasicSetting_UserInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="U_UserInfoEntity", Namespace="http://schemas.datacontract.org/2004/07/JSBR.Model.BaseTable.Entity")]
    [System.SerializableAttribute()]
    public partial class U_UserInfoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _CouIntroduceField;
        
        private string _CouSkilledFieldField;
        
        private string _RFtypeField;
        
        private int _activatenterprisemarkField;
        
        private string _activationsnumberField;
        
        private string _department_idField;
        
        private string _departmentauthorityField;
        
        private string _enterpriseCodeField;
        
        private int _isenterprisemarkField;
        
        private string _r_idField;
        
        private string _role_typesField;
        
        private string _student_idField;
        
        private string _u_addfieldField;
        
        private string _u_addressField;
        
        private string _u_ageField;
        
        private string _u_auditidField;
        
        private string _u_auditstateField;
        
        private string _u_audittimeField;
        
        private string _u_birthdayField;
        
        private string _u_emailField;
        
        private int _u_idField;
        
        private string _u_imgField;
        
        private int _u_isactivateField;
        
        private string _u_loginnameField;
        
        private string _u_mark_deleteField;
        
        private string _u_nameField;
        
        private string _u_parentsemailField;
        
        private string _u_parentstelField;
        
        private string _u_passwordField;
        
        private string _u_remarkField;
        
        private string _u_sexField;
        
        private string _u_strField;
        
        private string _u_telField;
        
        private string _u_timeField;
        
        private string departmentNameField;
        
        private string role_describeField;
        
        private string role_typeField;
        
        private string u_createpersonField;
        
        private string u_createtimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CouIntroduce {
            get {
                return this._CouIntroduceField;
            }
            set {
                if ((object.ReferenceEquals(this._CouIntroduceField, value) != true)) {
                    this._CouIntroduceField = value;
                    this.RaisePropertyChanged("_CouIntroduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CouSkilledField {
            get {
                return this._CouSkilledFieldField;
            }
            set {
                if ((object.ReferenceEquals(this._CouSkilledFieldField, value) != true)) {
                    this._CouSkilledFieldField = value;
                    this.RaisePropertyChanged("_CouSkilledField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _RFtype {
            get {
                return this._RFtypeField;
            }
            set {
                if ((object.ReferenceEquals(this._RFtypeField, value) != true)) {
                    this._RFtypeField = value;
                    this.RaisePropertyChanged("_RFtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _activatenterprisemark {
            get {
                return this._activatenterprisemarkField;
            }
            set {
                if ((this._activatenterprisemarkField.Equals(value) != true)) {
                    this._activatenterprisemarkField = value;
                    this.RaisePropertyChanged("_activatenterprisemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _activationsnumber {
            get {
                return this._activationsnumberField;
            }
            set {
                if ((object.ReferenceEquals(this._activationsnumberField, value) != true)) {
                    this._activationsnumberField = value;
                    this.RaisePropertyChanged("_activationsnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _department_id {
            get {
                return this._department_idField;
            }
            set {
                if ((object.ReferenceEquals(this._department_idField, value) != true)) {
                    this._department_idField = value;
                    this.RaisePropertyChanged("_department_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _departmentauthority {
            get {
                return this._departmentauthorityField;
            }
            set {
                if ((object.ReferenceEquals(this._departmentauthorityField, value) != true)) {
                    this._departmentauthorityField = value;
                    this.RaisePropertyChanged("_departmentauthority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _enterpriseCode {
            get {
                return this._enterpriseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this._enterpriseCodeField, value) != true)) {
                    this._enterpriseCodeField = value;
                    this.RaisePropertyChanged("_enterpriseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _isenterprisemark {
            get {
                return this._isenterprisemarkField;
            }
            set {
                if ((this._isenterprisemarkField.Equals(value) != true)) {
                    this._isenterprisemarkField = value;
                    this.RaisePropertyChanged("_isenterprisemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _r_id {
            get {
                return this._r_idField;
            }
            set {
                if ((object.ReferenceEquals(this._r_idField, value) != true)) {
                    this._r_idField = value;
                    this.RaisePropertyChanged("_r_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _role_types {
            get {
                return this._role_typesField;
            }
            set {
                if ((object.ReferenceEquals(this._role_typesField, value) != true)) {
                    this._role_typesField = value;
                    this.RaisePropertyChanged("_role_types");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _student_id {
            get {
                return this._student_idField;
            }
            set {
                if ((object.ReferenceEquals(this._student_idField, value) != true)) {
                    this._student_idField = value;
                    this.RaisePropertyChanged("_student_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_addfield {
            get {
                return this._u_addfieldField;
            }
            set {
                if ((object.ReferenceEquals(this._u_addfieldField, value) != true)) {
                    this._u_addfieldField = value;
                    this.RaisePropertyChanged("_u_addfield");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_address {
            get {
                return this._u_addressField;
            }
            set {
                if ((object.ReferenceEquals(this._u_addressField, value) != true)) {
                    this._u_addressField = value;
                    this.RaisePropertyChanged("_u_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_age {
            get {
                return this._u_ageField;
            }
            set {
                if ((object.ReferenceEquals(this._u_ageField, value) != true)) {
                    this._u_ageField = value;
                    this.RaisePropertyChanged("_u_age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_auditid {
            get {
                return this._u_auditidField;
            }
            set {
                if ((object.ReferenceEquals(this._u_auditidField, value) != true)) {
                    this._u_auditidField = value;
                    this.RaisePropertyChanged("_u_auditid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_auditstate {
            get {
                return this._u_auditstateField;
            }
            set {
                if ((object.ReferenceEquals(this._u_auditstateField, value) != true)) {
                    this._u_auditstateField = value;
                    this.RaisePropertyChanged("_u_auditstate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_audittime {
            get {
                return this._u_audittimeField;
            }
            set {
                if ((object.ReferenceEquals(this._u_audittimeField, value) != true)) {
                    this._u_audittimeField = value;
                    this.RaisePropertyChanged("_u_audittime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_birthday {
            get {
                return this._u_birthdayField;
            }
            set {
                if ((object.ReferenceEquals(this._u_birthdayField, value) != true)) {
                    this._u_birthdayField = value;
                    this.RaisePropertyChanged("_u_birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_email {
            get {
                return this._u_emailField;
            }
            set {
                if ((object.ReferenceEquals(this._u_emailField, value) != true)) {
                    this._u_emailField = value;
                    this.RaisePropertyChanged("_u_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _u_id {
            get {
                return this._u_idField;
            }
            set {
                if ((this._u_idField.Equals(value) != true)) {
                    this._u_idField = value;
                    this.RaisePropertyChanged("_u_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_img {
            get {
                return this._u_imgField;
            }
            set {
                if ((object.ReferenceEquals(this._u_imgField, value) != true)) {
                    this._u_imgField = value;
                    this.RaisePropertyChanged("_u_img");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _u_isactivate {
            get {
                return this._u_isactivateField;
            }
            set {
                if ((this._u_isactivateField.Equals(value) != true)) {
                    this._u_isactivateField = value;
                    this.RaisePropertyChanged("_u_isactivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_loginname {
            get {
                return this._u_loginnameField;
            }
            set {
                if ((object.ReferenceEquals(this._u_loginnameField, value) != true)) {
                    this._u_loginnameField = value;
                    this.RaisePropertyChanged("_u_loginname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_mark_delete {
            get {
                return this._u_mark_deleteField;
            }
            set {
                if ((object.ReferenceEquals(this._u_mark_deleteField, value) != true)) {
                    this._u_mark_deleteField = value;
                    this.RaisePropertyChanged("_u_mark_delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_name {
            get {
                return this._u_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._u_nameField, value) != true)) {
                    this._u_nameField = value;
                    this.RaisePropertyChanged("_u_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_parentsemail {
            get {
                return this._u_parentsemailField;
            }
            set {
                if ((object.ReferenceEquals(this._u_parentsemailField, value) != true)) {
                    this._u_parentsemailField = value;
                    this.RaisePropertyChanged("_u_parentsemail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_parentstel {
            get {
                return this._u_parentstelField;
            }
            set {
                if ((object.ReferenceEquals(this._u_parentstelField, value) != true)) {
                    this._u_parentstelField = value;
                    this.RaisePropertyChanged("_u_parentstel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_password {
            get {
                return this._u_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this._u_passwordField, value) != true)) {
                    this._u_passwordField = value;
                    this.RaisePropertyChanged("_u_password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_remark {
            get {
                return this._u_remarkField;
            }
            set {
                if ((object.ReferenceEquals(this._u_remarkField, value) != true)) {
                    this._u_remarkField = value;
                    this.RaisePropertyChanged("_u_remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_sex {
            get {
                return this._u_sexField;
            }
            set {
                if ((object.ReferenceEquals(this._u_sexField, value) != true)) {
                    this._u_sexField = value;
                    this.RaisePropertyChanged("_u_sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_str {
            get {
                return this._u_strField;
            }
            set {
                if ((object.ReferenceEquals(this._u_strField, value) != true)) {
                    this._u_strField = value;
                    this.RaisePropertyChanged("_u_str");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_tel {
            get {
                return this._u_telField;
            }
            set {
                if ((object.ReferenceEquals(this._u_telField, value) != true)) {
                    this._u_telField = value;
                    this.RaisePropertyChanged("_u_tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _u_time {
            get {
                return this._u_timeField;
            }
            set {
                if ((object.ReferenceEquals(this._u_timeField, value) != true)) {
                    this._u_timeField = value;
                    this.RaisePropertyChanged("_u_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string departmentName {
            get {
                return this.departmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentNameField, value) != true)) {
                    this.departmentNameField = value;
                    this.RaisePropertyChanged("departmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string role_describe {
            get {
                return this.role_describeField;
            }
            set {
                if ((object.ReferenceEquals(this.role_describeField, value) != true)) {
                    this.role_describeField = value;
                    this.RaisePropertyChanged("role_describe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string role_type {
            get {
                return this.role_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.role_typeField, value) != true)) {
                    this.role_typeField = value;
                    this.RaisePropertyChanged("role_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string u_createperson {
            get {
                return this.u_createpersonField;
            }
            set {
                if ((object.ReferenceEquals(this.u_createpersonField, value) != true)) {
                    this.u_createpersonField = value;
                    this.RaisePropertyChanged("u_createperson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string u_createtime {
            get {
                return this.u_createtimeField;
            }
            set {
                if ((object.ReferenceEquals(this.u_createtimeField, value) != true)) {
                    this.u_createtimeField = value;
                    this.RaisePropertyChanged("u_createtime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounselorModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.BasicSettingModel")]
    [System.SerializableAttribute()]
    public partial class CounselorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouIntroduceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouSkilledFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CounseTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CouIntroduce {
            get {
                return this.CouIntroduceField;
            }
            set {
                if ((object.ReferenceEquals(this.CouIntroduceField, value) != true)) {
                    this.CouIntroduceField = value;
                    this.RaisePropertyChanged("CouIntroduce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CouSkilledField {
            get {
                return this.CouSkilledFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CouSkilledFieldField, value) != true)) {
                    this.CouSkilledFieldField = value;
                    this.RaisePropertyChanged("CouSkilledField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CounseType {
            get {
                return this.CounseTypeField;
            }
            set {
                if ((this.CounseTypeField.Equals(value) != true)) {
                    this.CounseTypeField = value;
                    this.RaisePropertyChanged("CounseType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchaddModel", Namespace="http://schemas.datacontract.org/2004/07/BasicsServiceMODEL.BasicSettingModel")]
    [System.SerializableAttribute()]
    public partial class BatchaddModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatePepleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterpriseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PwdRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserName03Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserName04Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nametypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string username_tyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatePeple {
            get {
                return this.CreatePepleField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatePepleField, value) != true)) {
                    this.CreatePepleField = value;
                    this.RaisePropertyChanged("CreatePeple");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseCode {
            get {
                return this.EnterpriseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseCodeField, value) != true)) {
                    this.EnterpriseCodeField = value;
                    this.RaisePropertyChanged("EnterpriseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumEnd {
            get {
                return this.NumEndField;
            }
            set {
                if ((this.NumEndField.Equals(value) != true)) {
                    this.NumEndField = value;
                    this.RaisePropertyChanged("NumEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumStart {
            get {
                return this.NumStartField;
            }
            set {
                if ((this.NumStartField.Equals(value) != true)) {
                    this.NumStartField = value;
                    this.RaisePropertyChanged("NumStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pwd {
            get {
                return this.PwdField;
            }
            set {
                if ((object.ReferenceEquals(this.PwdField, value) != true)) {
                    this.PwdField = value;
                    this.RaisePropertyChanged("Pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PwdR {
            get {
                return this.PwdRField;
            }
            set {
                if ((object.ReferenceEquals(this.PwdRField, value) != true)) {
                    this.PwdRField = value;
                    this.RaisePropertyChanged("PwdR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string R_ID {
            get {
                return this.R_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.R_IDField, value) != true)) {
                    this.R_IDField = value;
                    this.RaisePropertyChanged("R_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName03 {
            get {
                return this.UserName03Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserName03Field, value) != true)) {
                    this.UserName03Field = value;
                    this.RaisePropertyChanged("UserName03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName04 {
            get {
                return this.UserName04Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserName04Field, value) != true)) {
                    this.UserName04Field = value;
                    this.RaisePropertyChanged("UserName04");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNameR {
            get {
                return this.UserNameRField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameRField, value) != true)) {
                    this.UserNameRField = value;
                    this.RaisePropertyChanged("UserNameR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nametype {
            get {
                return this.nametypeField;
            }
            set {
                if ((this.nametypeField.Equals(value) != true)) {
                    this.nametypeField = value;
                    this.RaisePropertyChanged("nametype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username_ty {
            get {
                return this.username_tyField;
            }
            set {
                if ((object.ReferenceEquals(this.username_tyField, value) != true)) {
                    this.username_tyField = value;
                    this.RaisePropertyChanged("username_ty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BasicSetting_UserInfo.IBasicSetting_UserInfo")]
    public interface IBasicSetting_UserInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/U_UserInfoAdd", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/U_UserInfoAddResponse")]
        bool U_UserInfoAdd(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/U_UserInfoAddTwo", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/U_UserInfoAddTwoResponse")]
        bool U_UserInfoAddTwo(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model, WebPages.BasicSetting_UserInfo.CounselorModel CounselorModels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserInfoList", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserInfoListResponse")]
        System.Data.DataSet GetUserInfoList(string loginName, int U_ID, int R_ID, string Name, string Department_ID, string RoleName, string U_Sex, string EnterpriseCode, int StarPageIndex, int EndPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetRoleTypeTemp", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetRoleTypeTempResponse")]
        System.Data.DataTable GetRoleTypeTemp(int userID, int role_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/Exceldt", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/ExceldtResponse")]
        System.Data.DataTable Exceldt(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserList", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserListResponse")]
        WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetUserList(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/ExcelImport", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/ExcelImportResponse")]
        string ExcelImport(System.Data.DataTable dt, string Name, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/deleteUser", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/deleteUserResponse")]
        bool deleteUser(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdatePwd", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdatePwdResponse")]
        bool UpdatePwd(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdatePwdByID", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdatePwdByIDResponse")]
        bool UpdatePwdByID(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/Mark_Delete", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/Mark_DeleteResponse")]
        bool Mark_Delete(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/Mark_Deletes", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/Mark_DeletesResponse")]
        bool Mark_Deletes(string UserIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateUserInfo", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateUserInfoResponse")]
        bool UpdateUserInfo(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateUserInfoTwo", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateUserInfoTwoResponse")]
        bool UpdateUserInfoTwo(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model, WebPages.BasicSetting_UserInfo.CounselorModel CounselorModels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetAuditList", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetAuditListResponse")]
        System.Data.DataSet GetAuditList(string U_AuditType, int StarPageIndex, int EndPageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateAccepByID", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateAccepByIDResponse")]
        bool UpdateAccepByID(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateAccep", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateAccepResponse")]
        bool UpdateAccep(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateRefuseByID", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateRefuseByIDResponse")]
        bool UpdateRefuseByID(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateRefuse", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateRefuseResponse")]
        bool UpdateRefuse(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/IsExistsUser", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/IsExistsUserResponse")]
        bool IsExistsUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/CheckUserIsActivate", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/CheckUserIsActivateResponse")]
        bool CheckUserIsActivate(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/Login", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/LoginResponse")]
        int Login(string loginName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetEntity", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetEntityResponse")]
        WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetEntity(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/Batchadd", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/BatchaddResponse")]
        int Batchadd(WebPages.BasicSetting_UserInfo.BatchaddModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/IsExistsUsers", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/IsExistsUsersResponse")]
        bool IsExistsUsers(string userName, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetEntitys", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetEntitysResponse")]
        WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetEntitys(int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserIDByLoginName", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserIDByLoginNameResponse")]
        int GetUserIDByLoginName(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserEmailByUserID", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserEmailByUserIDResponse")]
        string GetUserEmailByUserID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserFun", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserFunResponse")]
        System.Data.DataTable GetUserFun(string LoginName, int Fun_ParentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetTree", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetTreeResponse")]
        System.Data.DataTable GetTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserEmail", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserEmailResponse")]
        System.Data.DataTable GetUserEmail(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/Update_Delete", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/Update_DeleteResponse")]
        bool Update_Delete(int U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/Update_Deletes", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/Update_DeletesResponse")]
        bool Update_Deletes(string U_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/deleteUsers", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/deleteUsersResponse")]
        bool deleteUsers(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/RID", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/RIDResponse")]
        string RID(string RoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/updetapwds", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/updetapwdsResponse")]
        bool updetapwds(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/SelectR_ID", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/SelectR_IDResponse")]
        string SelectR_ID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateIsEActive", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateIsEActiveResponse")]
        bool UpdateIsEActive(string LoginName, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserRoleType", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserRoleTypeResponse")]
        int GetUserRoleType(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetAdminInfoByUserID", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetAdminInfoByUserIDResponse")]
        System.Data.DataTable GetAdminInfoByUserID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/IsExistsUserByE", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/IsExistsUserByEResponse")]
        bool IsExistsUserByE(string ECode, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetEntityInfo", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetEntityInfoResponse")]
        WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetEntityInfo(string loginName, string EnterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateDelete", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateDeleteResponse")]
        bool UpdateDelete(WebPages.BasicSetting_UserInfo.U_UserInfoEntity entityInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/UpdateInsert", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/UpdateInsertResponse")]
        bool UpdateInsert(WebPages.BasicSetting_UserInfo.U_UserInfoEntity entityInfo, WebPages.BasicSetting_UserInfo.CounselorModel CounselorModels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/CheckUserIsExist", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/CheckUserIsExistResponse")]
        int CheckUserIsExist(string loginName, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetUserIDByRoleAndEnterpriseCode", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetUserIDByRoleAndEnterpriseCodeRespons" +
            "e")]
        System.Collections.Generic.List<int> GetUserIDByRoleAndEnterpriseCode(int roleID, string enterpriseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/AddCounselor", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/AddCounselorResponse")]
        void AddCounselor(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/DeleteCounselor", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/DeleteCounselorResponse")]
        int DeleteCounselor(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/GetRoleTypeTempBath", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/GetRoleTypeTempBathResponse")]
        System.Data.DataTable GetRoleTypeTempBath(int userID, int role_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicSetting_UserInfo/IsBannedOfCheckEnterpriseCode", ReplyAction="http://tempuri.org/IBasicSetting_UserInfo/IsBannedOfCheckEnterpriseCodeResponse")]
        int IsBannedOfCheckEnterpriseCode(string enterpriseCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBasicSetting_UserInfoChannel : WebPages.BasicSetting_UserInfo.IBasicSetting_UserInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicSetting_UserInfoClient : System.ServiceModel.ClientBase<WebPages.BasicSetting_UserInfo.IBasicSetting_UserInfo>, WebPages.BasicSetting_UserInfo.IBasicSetting_UserInfo {
        
        public BasicSetting_UserInfoClient() {
        }
        
        public BasicSetting_UserInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicSetting_UserInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicSetting_UserInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicSetting_UserInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool U_UserInfoAdd(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model) {
            return base.Channel.U_UserInfoAdd(model);
        }
        
        public bool U_UserInfoAddTwo(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model, WebPages.BasicSetting_UserInfo.CounselorModel CounselorModels) {
            return base.Channel.U_UserInfoAddTwo(model, CounselorModels);
        }
        
        public System.Data.DataSet GetUserInfoList(string loginName, int U_ID, int R_ID, string Name, string Department_ID, string RoleName, string U_Sex, string EnterpriseCode, int StarPageIndex, int EndPageIndex) {
            return base.Channel.GetUserInfoList(loginName, U_ID, R_ID, Name, Department_ID, RoleName, U_Sex, EnterpriseCode, StarPageIndex, EndPageIndex);
        }
        
        public System.Data.DataTable GetRoleTypeTemp(int userID, int role_type) {
            return base.Channel.GetRoleTypeTemp(userID, role_type);
        }
        
        public System.Data.DataTable Exceldt(System.Data.DataTable dt) {
            return base.Channel.Exceldt(dt);
        }
        
        public WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetUserList(int UserID) {
            return base.Channel.GetUserList(UserID);
        }
        
        public string ExcelImport(System.Data.DataTable dt, string Name, string EnterpriseCode) {
            return base.Channel.ExcelImport(dt, Name, EnterpriseCode);
        }
        
        public bool deleteUser(int UserID) {
            return base.Channel.deleteUser(UserID);
        }
        
        public bool UpdatePwd(string UserID) {
            return base.Channel.UpdatePwd(UserID);
        }
        
        public bool UpdatePwdByID(int UserID) {
            return base.Channel.UpdatePwdByID(UserID);
        }
        
        public bool Mark_Delete(int UserID) {
            return base.Channel.Mark_Delete(UserID);
        }
        
        public bool Mark_Deletes(string UserIDs) {
            return base.Channel.Mark_Deletes(UserIDs);
        }
        
        public bool UpdateUserInfo(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model) {
            return base.Channel.UpdateUserInfo(model);
        }
        
        public bool UpdateUserInfoTwo(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model, WebPages.BasicSetting_UserInfo.CounselorModel CounselorModels) {
            return base.Channel.UpdateUserInfoTwo(model, CounselorModels);
        }
        
        public System.Data.DataSet GetAuditList(string U_AuditType, int StarPageIndex, int EndPageIndex) {
            return base.Channel.GetAuditList(U_AuditType, StarPageIndex, EndPageIndex);
        }
        
        public bool UpdateAccepByID(int UserID) {
            return base.Channel.UpdateAccepByID(UserID);
        }
        
        public bool UpdateAccep(string UserID) {
            return base.Channel.UpdateAccep(UserID);
        }
        
        public bool UpdateRefuseByID(int UserID) {
            return base.Channel.UpdateRefuseByID(UserID);
        }
        
        public bool UpdateRefuse(string UserID) {
            return base.Channel.UpdateRefuse(UserID);
        }
        
        public bool IsExistsUser(string userName) {
            return base.Channel.IsExistsUser(userName);
        }
        
        public bool CheckUserIsActivate(string loginName) {
            return base.Channel.CheckUserIsActivate(loginName);
        }
        
        public int Login(string loginName, string pwd) {
            return base.Channel.Login(loginName, pwd);
        }
        
        public WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetEntity(string loginName) {
            return base.Channel.GetEntity(loginName);
        }
        
        public int Batchadd(WebPages.BasicSetting_UserInfo.BatchaddModel model) {
            return base.Channel.Batchadd(model);
        }
        
        public bool IsExistsUsers(string userName, int UserID) {
            return base.Channel.IsExistsUsers(userName, UserID);
        }
        
        public WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetEntitys(int U_ID) {
            return base.Channel.GetEntitys(U_ID);
        }
        
        public int GetUserIDByLoginName(string loginName) {
            return base.Channel.GetUserIDByLoginName(loginName);
        }
        
        public string GetUserEmailByUserID(int userID) {
            return base.Channel.GetUserEmailByUserID(userID);
        }
        
        public System.Data.DataTable GetUserFun(string LoginName, int Fun_ParentID) {
            return base.Channel.GetUserFun(LoginName, Fun_ParentID);
        }
        
        public System.Data.DataTable GetTree() {
            return base.Channel.GetTree();
        }
        
        public System.Data.DataTable GetUserEmail(string userID) {
            return base.Channel.GetUserEmail(userID);
        }
        
        public bool Update_Delete(int U_ID) {
            return base.Channel.Update_Delete(U_ID);
        }
        
        public bool Update_Deletes(string U_ID) {
            return base.Channel.Update_Deletes(U_ID);
        }
        
        public bool deleteUsers(string UserID) {
            return base.Channel.deleteUsers(UserID);
        }
        
        public string RID(string RoleName) {
            return base.Channel.RID(RoleName);
        }
        
        public bool updetapwds(WebPages.BasicSetting_UserInfo.U_UserInfoEntity model) {
            return base.Channel.updetapwds(model);
        }
        
        public string SelectR_ID() {
            return base.Channel.SelectR_ID();
        }
        
        public bool UpdateIsEActive(string LoginName, string EnterpriseCode) {
            return base.Channel.UpdateIsEActive(LoginName, EnterpriseCode);
        }
        
        public int GetUserRoleType(int userID) {
            return base.Channel.GetUserRoleType(userID);
        }
        
        public System.Data.DataTable GetAdminInfoByUserID(int userID) {
            return base.Channel.GetAdminInfoByUserID(userID);
        }
        
        public bool IsExistsUserByE(string ECode, string userName) {
            return base.Channel.IsExistsUserByE(ECode, userName);
        }
        
        public WebPages.BasicSetting_UserInfo.U_UserInfoEntity GetEntityInfo(string loginName, string EnterpriseCode) {
            return base.Channel.GetEntityInfo(loginName, EnterpriseCode);
        }
        
        public bool UpdateDelete(WebPages.BasicSetting_UserInfo.U_UserInfoEntity entityInfo) {
            return base.Channel.UpdateDelete(entityInfo);
        }
        
        public bool UpdateInsert(WebPages.BasicSetting_UserInfo.U_UserInfoEntity entityInfo, WebPages.BasicSetting_UserInfo.CounselorModel CounselorModels) {
            return base.Channel.UpdateInsert(entityInfo, CounselorModels);
        }
        
        public int CheckUserIsExist(string loginName, string enterpriseCode) {
            return base.Channel.CheckUserIsExist(loginName, enterpriseCode);
        }
        
        public System.Collections.Generic.List<int> GetUserIDByRoleAndEnterpriseCode(int roleID, string enterpriseCode) {
            return base.Channel.GetUserIDByRoleAndEnterpriseCode(roleID, enterpriseCode);
        }
        
        public void AddCounselor(System.Data.DataTable dt) {
            base.Channel.AddCounselor(dt);
        }
        
        public int DeleteCounselor(string userID) {
            return base.Channel.DeleteCounselor(userID);
        }
        
        public System.Data.DataTable GetRoleTypeTempBath(int userID, int role_type) {
            return base.Channel.GetRoleTypeTempBath(userID, role_type);
        }
        
        public int IsBannedOfCheckEnterpriseCode(string enterpriseCode) {
            return base.Channel.IsBannedOfCheckEnterpriseCode(enterpriseCode);
        }
    }
}
