//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.StatisticalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatisticalService.IStatisticalService")]
    public interface IStatisticalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticalService/GetStatisticaUser", ReplyAction="http://tempuri.org/IStatisticalService/GetStatisticaUserResponse")]
        System.Data.DataSet GetStatisticaUser(int userID, int userRoleType, string Amount_Code, int DepartmentID, string Sex, string EnterpriseCode, int StartIndex, int EndIndex, System.DateTime S_Time, System.DateTime E_Time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticalService/GetTestType", ReplyAction="http://tempuri.org/IStatisticalService/GetTestTypeResponse")]
        System.Data.DataTable GetTestType(string Amount_Code, int DepartmentID, string EnterpriseCode, System.DateTime S_Time, System.DateTime E_Time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticalService/GenerateLogic", ReplyAction="http://tempuri.org/IStatisticalService/GenerateLogicResponse")]
        string GenerateLogic(string XMLJson, string LB_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticalService/GetAnalyBaseTemp", ReplyAction="http://tempuri.org/IStatisticalService/GetAnalyBaseTempResponse")]
        System.Data.DataTable GetAnalyBaseTemp(string AnalyBaseMark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatisticalServiceChannel : WebPages.StatisticalService.IStatisticalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticalServiceClient : System.ServiceModel.ClientBase<WebPages.StatisticalService.IStatisticalService>, WebPages.StatisticalService.IStatisticalService {
        
        public StatisticalServiceClient() {
        }
        
        public StatisticalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetStatisticaUser(int userID, int userRoleType, string Amount_Code, int DepartmentID, string Sex, string EnterpriseCode, int StartIndex, int EndIndex, System.DateTime S_Time, System.DateTime E_Time) {
            return base.Channel.GetStatisticaUser(userID, userRoleType, Amount_Code, DepartmentID, Sex, EnterpriseCode, StartIndex, EndIndex, S_Time, E_Time);
        }
        
        public System.Data.DataTable GetTestType(string Amount_Code, int DepartmentID, string EnterpriseCode, System.DateTime S_Time, System.DateTime E_Time) {
            return base.Channel.GetTestType(Amount_Code, DepartmentID, EnterpriseCode, S_Time, E_Time);
        }
        
        public string GenerateLogic(string XMLJson, string LB_Code) {
            return base.Channel.GenerateLogic(XMLJson, LB_Code);
        }
        
        public System.Data.DataTable GetAnalyBaseTemp(string AnalyBaseMark) {
            return base.Channel.GetAnalyBaseTemp(AnalyBaseMark);
        }
    }
}
