//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.InspectionWarningService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InspectionWarningService.IInspectionWarningService")]
    public interface IInspectionWarningService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInspectionWarningService/Get_ShowIWTemp", ReplyAction="http://tempuri.org/IInspectionWarningService/Get_ShowIWTempResponse")]
        System.Data.DataSet Get_ShowIWTemp(System.DateTime StarTime, System.DateTime EndTime, string currentLoginName, string U_LoginName, string U_Sex, int Department_ID, string Amount_Code, string DimensionCode, int StartPage, int EndPage, string EnterpriseCode, int UID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInspectionWarningService/GetAmountList", ReplyAction="http://tempuri.org/IInspectionWarningService/GetAmountListResponse")]
        System.Data.DataTable GetAmountList(string LicenseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInspectionWarningService/GetA_WD", ReplyAction="http://tempuri.org/IInspectionWarningService/GetA_WDResponse")]
        System.Data.DataTable GetA_WD(string Acode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInspectionWarningService/DelCrisisListByCode", ReplyAction="http://tempuri.org/IInspectionWarningService/DelCrisisListByCodeResponse")]
        int DelCrisisListByCode(string C_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInspectionWarningService/DelCrisisListByCodeList", ReplyAction="http://tempuri.org/IInspectionWarningService/DelCrisisListByCodeListResponse")]
        int DelCrisisListByCodeList(string C_Code_Str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInspectionWarningServiceChannel : WebPages.InspectionWarningService.IInspectionWarningService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InspectionWarningServiceClient : System.ServiceModel.ClientBase<WebPages.InspectionWarningService.IInspectionWarningService>, WebPages.InspectionWarningService.IInspectionWarningService {
        
        public InspectionWarningServiceClient() {
        }
        
        public InspectionWarningServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InspectionWarningServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InspectionWarningServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InspectionWarningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_ShowIWTemp(System.DateTime StarTime, System.DateTime EndTime, string currentLoginName, string U_LoginName, string U_Sex, int Department_ID, string Amount_Code, string DimensionCode, int StartPage, int EndPage, string EnterpriseCode, int UID) {
            return base.Channel.Get_ShowIWTemp(StarTime, EndTime, currentLoginName, U_LoginName, U_Sex, Department_ID, Amount_Code, DimensionCode, StartPage, EndPage, EnterpriseCode, UID);
        }
        
        public System.Data.DataTable GetAmountList(string LicenseCode) {
            return base.Channel.GetAmountList(LicenseCode);
        }
        
        public System.Data.DataTable GetA_WD(string Acode) {
            return base.Channel.GetA_WD(Acode);
        }
        
        public int DelCrisisListByCode(string C_Code) {
            return base.Channel.DelCrisisListByCode(C_Code);
        }
        
        public int DelCrisisListByCodeList(string C_Code_Str) {
            return base.Channel.DelCrisisListByCodeList(C_Code_Str);
        }
    }
}
